In [ ]:
# 구글 드라이브 마운트하기
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd

In [ ]:
# 작업 디렉토리 지정하기
import os

wd = "/content/drive/MyDrive/data_handling_data"
os.chdir(wd)
os.getcwd()

'/content/drive/MyDrive/data_handling_data'

# [1] numpy

- NumPy(Numerical Python): 대규모 수치 연산과 배열 계산을 위한 라이브러리로 복잡한 수학·통계 연산에 적합

**특징**

(1) 내부적으로 C 언어를 기반으로 하고 있어 연산 속도가 빠르다.

(2) `numpy`를 기반으로 한 다른 라이브러리가 많다(예: `pandas`, `scikit-learn`, `scipy`, `tensorflow` 등)

## (1) array

### array 생성하기

- `np.array()` : 파이썬의 리스트(list)나 튜플(tuple) 등을 numpy의 ndarray 객체로 변환하는 함수
- `np.zeros(n)` : 0이 n개 들어있는 배열 생성  
- `np.ones(n)` : 1이 n개 들어있는 배열 생성  
- `np.arange(a)` : 0 이상 a 미만의 정수 배열 생성  
- `np.arange(a, b)` : a 이상 b 미만의 정수 배열 생성  
- `np.arange(a, b, c)` : a 이상 b 미만, c 간격의 배열 생성

In [ ]:
# 라이브러리 불러오기
import numpy as np

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4, 17, 3)

array([ 4,  7, 10, 13, 16])

- `np.random.randint`(a, b, size=n) : a 이상 b 미만 n개 정수 난수 생성
- `np.random.choice`(list, size=n) : 리스트에서 n개 샘플 추출
- `np.random.normal`(loc, scale, size=n) : 평균(loc), 표준편차(scale)의 정규 분포 난수 n개 생성
- `np.linspace`(a, b, num=n) : a부터 b까지 n개 균등 분할, 일정 간격의 수열 생성

In [ ]:
# 0 이상 10 미만 정수 5개
np.random.randint(0, 10, size=5)

array([2, 3, 3, 5, 8])

In [ ]:
# 리스트에서 3개 랜덤 추출(기본값 : replace=True(중복 허용 추출))
np.random.choice(['A', 'B', 'C', 'D'], size=3)

array(['C', 'B', 'C'], dtype='<U1')

In [ ]:
# 리스트에서 중복 없이 3개 랜덤 추출
np.random.choice(['A', 'B', 'C', 'D'], size=3, replace=False)

array(['A', 'B', 'D'], dtype='<U1')

In [ ]:
# 평균 50, 표준편차 10인 정규 분포에서 난수 5개 생성
np.random.normal(loc=50, scale=10, size=5)

array([48.07359594, 53.27142844, 49.32889816, 34.18752591, 46.72443747])

In [ ]:
# 10부터 100까지 10개 균등 분할
np.linspace(10, 100, num=10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bool, optional
        If True, return (`samples`, `step`), where `step` is the spacing
        between samples.
    dtype : dtype, optional
        The type of the output array.  If `dtype` is not given, the data type
        is inferred from `start` and `stop`. The inferred dtype will never be
        an integer; `float` is chosen even if the arguments would produce an
        array of integers.

        .. versionadded:: 1.9.0
    axis : int, optional
        The axis in the result to store the samples.  Relevant only if start
        or stop are array-like.  By default (0), the samples will be along a
        new axis inserted at the beginning. Use -1 to get an axis at the end.

        .. versionadded:: 1.16.0
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0

    Returns
    -------
    samples : ndarray
        There are `num` equally spaced samples in the closed interval
        ``[start, stop]`` or the half-open interval ``[start, stop)``
        (depending on whether `endpoint` is True or False).
    step : float, optional
        Only returned if `retstep` is True

        Size of spacing between samples.


    See Also
    --------
    arange : Similar to `linspace`, but uses a step size (instead of the
             number of samples).
    geomspace : Similar to `linspace`, but with numbers spaced evenly on a log
                scale (a geometric progression).
    logspace : Similar to `geomspace`, but with the end points specified as
               logarithms.
    :ref:`how-to-partition`

    Examples
    --------
    >>> np.linspace(2.0, 3.0, num=5)
    array([2.  , 2.25, 2.5 , 2.75, 3.  ])
    >>> np.linspace(2.0, 3.0, num=5, endpoint=False)
    array([2. ,  2.2,  2.4,  2.6,  2.8])
    >>> np.linspace(2.0, 3.0, num=5, retstep=True)
    (array([2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)

    Graphical illustration:

    >>> import matplotlib.pyplot as plt
    >>> N = 8
    >>> y = np.zeros(N)
    >>> x1 = np.linspace(0, 10, N, endpoint=True)
    >>> x2 = np.linspace(0, 10, N, endpoint=False)
    >>> plt.plot(x1, y, 'o')
    [<matplotlib.lines.Line2D object at 0x...>]
    >>> plt.plot(x2, y + 0.5, 'o')
    [<matplotlib.lines.Line2D object at 0x...>]
    >>> plt.ylim([-0.5, 1])
    (-0.5, 1)
    >>> plt.show()

- `size` : 배열에 들어 있는 전체 원소(요소)의 개수
- `shape` : 배열의 차원 구조(행, 열 개수)를 튜플로 반환
- `ndim` : 차원의 개수(축의 개수)

In [ ]:
array1 = np.array([1, 3, 5, 6, 7, 9])
array1

array([1, 3, 5, 6, 7, 9])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
array1.size

6

In [ ]:
array1.shape

(6,)

In [ ]:
array1.ndim

1

In [ ]:
array2 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
array2.size

12

In [ ]:
array2.shape

(3, 4)

In [ ]:
array2.ndim

2

### 1차원 array

In [ ]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])
gdp_array

array([ 6610,  7637,  8127,  8885, 10385, 12565, 13403, 12398,  8282,
       10672])

- 인덱싱(indexing) : 배열이나 데이터에서 하나의 위치를 지정해 단일 요소를 선택하는 것
- 슬라이싱(slicing) : 시작화 끝 범위를 지정해 여러 요소를 연속적으로 선택하는 것

In [ ]:
gdp_array[0]

np.int64(6610)

In [ ]:
gdp_array[-1]

np.int64(10672)

In [ ]:
gdp_array[[1, 3, 4]]

array([ 7637,  8885, 10385])

In [ ]:
gdp_array[2:6]

array([ 8127,  8885, 10385, 12565])

In [ ]:
gdp_array[:6]

array([ 6610,  7637,  8127,  8885, 10385, 12565])

In [ ]:
gdp_array[5:]

array([12565, 13403, 12398,  8282, 10672])

In [ ]:
gdp_array[1:8:3]

array([ 7637, 10385, 12398])

### 2차원 array

In [ ]:
gdp_array = np.array([
    [1, 2, 3, 4, 5, 6],  # 대한민국
    [7, 8, 9, 10, 11, 12],  # 일본
    [13, 14, 15, 16, 17, 18],  # 중국
    [19, 20, 21, 22, 23, 24]   # 미국
])

gdp_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
gdp_array[1][3]

np.int64(10)

In [ ]:
gdp_array[1, 3]

np.int64(10)

In [ ]:
gdp_array[1:3]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
gdp_array[1:3, 2:5]

array([[ 9, 10, 11],
       [15, 16, 17]])

## (2) 조건에 맞는 데이터 선택하기

- 불린 인덱싱(`Boolean Indexing`) : 조건식의 결과로 나온 `True/False`값을 이용해, 원하는 데이터만 선택하는 방법
- 원리: 조건을 만족하는 행(또는 열)은 `True`로 표시하고, 조건을 만족하지 않으면 `False`로 숨김
- 예시: 특정 값 이상인 데이터, 특정 조건을 만족하는 행만 필터링

(예시1)

In [ ]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 14403, 12398, 8282, 10672])
gdp_array

array([ 6610,  7637,  8127,  8885, 10385, 12565, 14403, 12398,  8282,
       10672])

In [ ]:
# gdp가 10000 초과인 경우
gdp_array[gdp_array > 10000]

array([10385, 12565, 14403, 12398, 10672])

In [ ]:
mask = gdp_array > 10000
gdp_array[mask]

array([10385, 12565, 14403, 12398, 10672])

(예시2)

In [ ]:
gdp_array

array([ 6610,  7637,  8127,  8885, 10385, 12565, 14403, 12398,  8282,
       10672])

In [ ]:
# gdp가 8000 이상이고, 10000 이하인 경우
gdp_array[(gdp_array >= 8000) & (gdp_array <= 10000)]

array([8127, 8885, 8282])

In [ ]:
condition = (gdp_array >= 8000) & (gdp_array <= 10000)
gdp_array[condition]

array([8127, 8885, 8282])

In [ ]:
condition1 = (gdp_array >= 8000)
condition2 = (gdp_array <= 10000)
gdp_array[condition1 & condition2]

array([8127, 8885, 8282])

(예시3)

In [ ]:
gdp_array

array([ 6610,  7637,  8127,  8885, 10385, 12565, 14403, 12398,  8282,
       10672])

In [ ]:
# gdp가 8000 미만 이거나 gdp가 10000 초과인 경우
gdp_array[(gdp_array < 8000) | (gdp_array > 10000)]

array([ 6610,  7637, 10385, 12565, 14403, 12398, 10672])

In [ ]:
condition = (gdp_array < 8000) | (gdp_array > 10000)
gdp_array[condition]

array([ 6610,  7637, 10385, 12565, 14403, 12398, 10672])

In [ ]:
condition1 = (gdp_array < 8000)
condition2 = (gdp_array > 10000)
gdp_array[condition1 | condition2]

array([ 6610,  7637, 10385, 12565, 14403, 12398, 10672])

## (3) 조건에 따라 값 변경하기

- `np.where` : 조건에 따라 값을 선택하거나 조건을 만족하는 위치를 반환하는 함수

```
np.where(조건, 참일 때 값, 거짓일 때 값)
```

In [ ]:
array = np.array([10, 25, 30, 15, 50])
array

array([10, 25, 30, 15, 50])

In [ ]:
# 조건 : 요소가 30 이상인 경우
array >= 30

array([False, False,  True, False,  True])

In [ ]:
np.where(array >= 30, "30이상", "30미만")

array(['30미만', '30미만', '30이상', '30미만', '30이상'], dtype='<U4')

## (4) 기본 연산

(사칙 연산)

In [ ]:
gdp_korea_array = np.array([12257, 11561, 13165, 14673, 16496, 19403])
gdp_korea_array

array([12257, 11561, 13165, 14673, 16496, 19403])

In [ ]:
gdp_us_array = np.array([36335, 37133, 38023, 39496, 41713, 44115])
gdp_us_array

array([36335, 37133, 38023, 39496, 41713, 44115])

(배열과 스칼라 연산)
- 모든 요소에 동일하게 적용

In [ ]:
# 1천 달러씩 증가한다고 가정
gdp_korea_array + 1000

array([13257, 12561, 14165, 15673, 17496, 20403])

In [ ]:
# 10% 증가
gdp_korea_array * 1.1

array([13482.7, 12717.1, 14481.5, 16140.3, 18145.6, 21343.3])

(배열과 배열 연산)
- 같은 위치의 요소끼리 계산

In [ ]:
gdp_korea_array

NameError: name 'gdp_korea_array' is not defined

In [ ]:
gdp_us_array

array([36335, 37133, 38023, 39496, 41713, 44115])

In [ ]:
gdp_korea_array + gdp_us_array

array([48592, 48694, 51188, 54169, 58209, 63518])

In [ ]:
gdp_korea_array - gdp_us_array

array([-24078, -25572, -24858, -24823, -25217, -24712])

In [ ]:
gdp_korea_array * gdp_us_array

array([445358095, 429294613, 500572795, 579524808, 688097648, 855963345])

In [ ]:
gdp_korea_array / gdp_us_array

array([0.33733315, 0.31134032, 0.3462378 , 0.37150598, 0.39546424,
       0.43982772])

(대표적인 함수)
- `mean` : 평균값
- `sum` : 합
- `min` : 최솟값
- `max` : 최댓값
- `std` : 표준편차
- `var` : 분산
- `round` : 반올림

In [ ]:
gdp_korea_array = np.array([12257, 11561, 13165, 14673, 16496, 19403])
gdp_korea_array

array([12257, 11561, 13165, 14673, 16496, 19403])

In [ ]:
# 평균
np.mean(gdp_korea_array)

np.float64(14592.5)

In [ ]:
# 합계
np.sum(gdp_korea_array)

np.int64(87555)

In [ ]:
# 최솟값
np.min(gdp_korea_array)

np.int64(11561)

In [ ]:
# 최댓값
np.max(gdp_korea_array)

np.int64(19403)

In [ ]:
# 표준편차
np.std(gdp_korea_array)

np.float64(2691.127753068095)

In [ ]:
# 분산
np.var(gdp_korea_array)

np.float64(7242168.583333333)

In [ ]:
# 반올림(예 : 표준편차 구한 뒤 반올림)
np.round(np.std(gdp_korea_array), 2)

np.float64(2691.13)

(축 지정)

- axis=0 : 행 방향으로 계산(각 열별로 계산)
- axis=1 : 열 방향으로 계산(각 행별로 계산)

In [ ]:
gdp_korea_array

array([12257, 11561, 13165, 14673, 16496, 19403])

In [ ]:
gdp_us_array

array([36335, 37133, 38023, 39496, 41713, 44115])

In [ ]:
gdp_2d = np.array([gdp_korea_array, gdp_us_array])
gdp_2d

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [ ]:
np.mean(gdp_2d)

np.float64(27030.833333333332)

In [ ]:
# 연도별 한국과 미국 GDP 평균
np.mean(gdp_2d, axis=0)

array([24296. , 24347. , 25594. , 27084.5, 29104.5, 31759. ])

In [ ]:
# 한국 GDP 평균, 미국 GDP 평균
np.mean(gdp_2d, axis=1)

array([14592.5       , 39469.16666667])

- `np.any()` : 조건을 만족하는 값이 하나라도 있으면 `True`

In [ ]:
gdp_korea_array

array([12257, 11561, 13165, 14673, 16496, 19403])

In [ ]:
# 한국 GDP가 18000 이상인 적이 있는지
np.any(gdp_korea_array >= 18000)

np.True_

In [ ]:
# 한국 GDP가 50000 이상인 적이 있는지
np.any(gdp_korea_array >= 50000)

np.False_

# [2] pandas
- `pandas`: 데이터를 표(데이터프레임) 형태로 다루고 분석하는 라이브러리
- 주요 기능:
  1. 데이터 불러오기
  2. 데이터 가공
  3. 데이터 분석
- `pandas`는 `numpy`를 기반으로 개발된 데이터 분석용 고수준 라이브러리이다. `numpy array`의 한계는 다음과 같다.
  1. 가독성이 떨어진다.
  2. 데이터에 레이블 삽입이 불가하다.
  3. 한 가지 데이터 타입만 사용 가능하다.

In [ ]:
# 라이브러리 불러오기
import pandas as pd

## (1) pandas 시작하기

### (a) DataFrame 생성하기

딕셔너리, 리스트, 배열을 사용해 `pd.DataFrame()`으로 데이터프레임을 만들어 보겠다.

(1-1) 딕셔너리 -> 데이터 프레임

In [ ]:
dict_data = {
    'category': ['skirt', 'sweater', 'coat', 'jeans'],
    'quantity': [10, 15, 6, 11],
    'price': [30000, 60000, 95000, 35000]
}

dict_data

{'category': ['skirt', 'sweater', 'coat', 'jeans'],
 'quantity': [10, 15, 6, 11],
 'price': [30000, 60000, 95000, 35000]}

In [ ]:
type(dict_data)

dict

In [ ]:
# 데이터 프레임
dict_df = pd.DataFrame(dict_data)

In [ ]:
dict_df

  category  quantity  price
0    skirt        10  30000
1  sweater        15  60000
2     coat         6  95000
3    jeans        11  35000

In [ ]:
type(dict_df)

pandas.core.frame.DataFrame

(1-2) 리스트 -> 데이터 프레임

(예시1)

In [ ]:
list_data = [
    ['skirt', 10, 30000],
    ['sweater', 15, 60000],
    ['coat', 6, 95000],
    ['jeans', 11, 35000]
]

list_data

[['skirt', 10, 30000],
 ['sweater', 15, 60000],
 ['coat', 6, 95000],
 ['jeans', 11, 35000]]

In [ ]:
type(list_data)

list

In [ ]:
# 데이터 프레임
list_df = pd.DataFrame(list_data)

In [ ]:
list_df

         0   1      2
0    skirt  10  30000
1  sweater  15  60000
2     coat   6  95000
3    jeans  11  35000

In [ ]:
type(list_df)

pandas.core.frame.DataFrame

In [ ]:
# 데이터 프레임
list_df = pd.DataFrame(list_data, columns=['category', 'quantity', 'price'])

In [ ]:
list_df

  category  quantity  price
0    skirt        10  30000
1  sweater        15  60000
2     coat         6  95000
3    jeans        11  35000

(예시2)

In [ ]:
dict_list = [
    {'category': 'skirt', 'quantity': 10, 'price': 30000},
    {'category': 'sweater', 'quantity': 15, 'price': 60000},
    {'category': 'coat', 'quantity': 6, 'price': 95000},
    {'category': 'jeans', 'quantity': 11, 'price': 35000}
]

dict_list

[{'category': 'skirt', 'quantity': 10, 'price': 30000},
 {'category': 'sweater', 'quantity': 15, 'price': 60000},
 {'category': 'coat', 'quantity': 6, 'price': 95000},
 {'category': 'jeans', 'quantity': 11, 'price': 35000}]

In [ ]:
type(dict_list)

list

In [ ]:
# 데이터 프레임
dict_list_df = pd.DataFrame(dict_list)

In [ ]:
dict_list_df

  category  quantity  price
0    skirt        10  30000
1  sweater        15  60000
2     coat         6  95000
3    jeans        11  35000

(1-3) 배열 -> 데이터 프레임

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
array_data = np.array([
    ['skirt', 10, 30000],
    ['sweater', 15, 60000],
    ['coat', 6, 95000],
    ['jeans', 11, 35000]
])

array_data

array([['skirt', '10', '30000'],
       ['sweater', '15', '60000'],
       ['coat', '6', '95000'],
       ['jeans', '11', '35000']], dtype='<U21')

In [ ]:
type(array_data)

numpy.ndarray

In [ ]:
# 데이터 프레임
array_df = pd.DataFrame(array_data)

In [ ]:
array_df

         0   1      2
0    skirt  10  30000
1  sweater  15  60000
2     coat   6  95000
3    jeans  11  35000

In [ ]:
type(array_df)

pandas.core.frame.DataFrame

In [ ]:
array_df = pd.DataFrame(array_data, columns=['category', 'quantity', 'price'])
array_df

  category quantity  price
0    skirt       10  30000
1  sweater       15  60000
2     coat        6  95000
3    jeans       11  35000

### (b) 파일 입출력(csv, Excel)

(csv, xlsx 파일을 불러오기)

1. `pd.read_csv` : csv 파일을 불러올 때 사용
2. `pd.read_excel` : xlsx 파일을 불러올 때 사용

In [ ]:
# 데이터 불러오기
pd.read_csv("/content/burger.csv")

In [ ]:
# 현재 작업 디렉토리 확인하기
import os

os.getcwd()

'/content'

In [ ]:
# 작업 디렉토리 변경하기
wd = "/content/drive/MyDrive/data_handling_data"
os.chdir(wd)

In [ ]:
# 현재 작업 디렉토리 확인하기
os.getcwd()

'/content/drive/MyDrive/data_handling_data'

- `pd.read_csv` : csv 파일을 불러올 때 사용

In [ ]:
# 데이터 불러오기
burger_df = pd.read_csv("burger.csv")

In [ ]:
burger_df.head()

            product_name  calories  carb  protein  fat  sodium category
0                Whopper       660    49       28   40     1.0  Burgers
1         Cheese Whopper       740    50       32   46     1.3  Burgers
2         Double Whopper       900    49       48   58     1.0  Burgers
3  Double Cheese Whopper       980    50       52   64     1.4  Burgers
4         Whopper Junior       310    27       13   18     0.4  Burgers

In [ ]:
# 데이터 불러오기
burger_df = pd.read_csv("burger.csv", index_col="product_name") # 어떤 컬럼을 인덱스로 하쉴?
burger_df.head()

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers

In [ ]:
burger_df = pd.read_csv("burger.csv", index_col="calories")
burger_df.head()

                   product_name  carb  protein  fat  sodium category
calories
660                     Whopper    49       28   40     1.0  Burgers
740              Cheese Whopper    50       32   46     1.3  Burgers
900              Double Whopper    49       48   58     1.0  Burgers
980       Double Cheese Whopper    50       52   64     1.4  Burgers
310              Whopper Junior    27       13   18     0.4  Burgers

In [ ]:
# 데이터 불러오기
burger_df = pd.read_csv("burger.csv", index_col=0)
burger_df.head()

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers

In [ ]:
# help(pd.read_csv)

- `pd.read_excel` : xlsx 파일을 불러올 때 사용
  - `header` : 열 이름이 있는 행 번호 지정
  - `sheet_name` : 불러올 시트 이름 또는 번호
  - `usecols` : 불러올 열 선택

In [ ]:
# help(pd.read_excel)

In [ ]:
# 데이터 불러오기
df = pd.read_excel("loan.xlsx", sheet_name = 1, header=3, usecols=range(1, 8))  # usecols='B:H', usecols=[1, 2, 3, 4, 5, 6, 7]

In [ ]:
df.head()

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y

(csv, xlsx 파일로 내보내기)

1. `df.to_csv` : 데이터 프레임을 csv 파일로 내보낼 때 사용
2. `df.to_excel` : 데이터 프레임을 xlsx 파일로 내보낼 때 사용
3. `pd.ExcelWriter` : 여러 개의 데이터 프레임을 하나의 엑셀 파일로 내보낼 때 사용

In [ ]:
# 국가별 GDP 데이터
df_gdp = pd.DataFrame({
    "Year": [2018, 2019, 2020, 2021],
    "Korea": [16496, 19403, 18240, 20734],
    "US": [41713, 44115, 43300, 48000]
})

# 연도별 인구 데이터
df_population = pd.DataFrame({
    "Year": [2018, 2019, 2020, 2021],
    "Korea_Pop": [51.6, 51.8, 51.7, 51.6],
    "US_Pop": [327, 329, 331, 333]
})

# 기업 매출 데이터
df_sales = pd.DataFrame({
    "Company": ["A", "B", "C", "D"],
    "Sales_2023": [120, 150, 90, 200],
    "Sales_2024": [140, 160, 110, 230]
})

- `df.to_csv` : 데이터 프레임을 csv 파일로 내보낼 때 사용

In [ ]:
df_sales

  Company  Sales_2023  Sales_2024
0       A         120         140
1       B         150         160
2       C          90         110
3       D         200         230

In [ ]:
df_sales.to_csv("/content/sales_2324.csv", index=False)

- `df.to_excel` : 데이터 프레임을 xlsx 파일로 내보낼 때 사용
  - `sheet_name` : 저장할 시트 이름
  - `startrow` : 저장 시작 행
  - `starcol` : 저장 시작 열
  - `index=False` : 인덱스를 저장하지 않음

In [ ]:
df_sales.to_excel("/content/sales_2324.xlsx",
                  sheet_name="sales",
                  startrow=1,
                  startcol=1,
                  index=False)

- `pd.ExcelWriter `: 여러 개의 데이터 프레임을 하나의 엑셀 파일로 내보낼 때 사용

In [ ]:
with pd.ExcelWriter("/content/kr_us.xlsx") as writer:
    df_gdp.to_excel(writer, sheet_name='gdp', index=False)
    df_population.to_excel(writer, sheet_name='population', index=False)

In [ ]:
df_gdp

   Year  Korea     US
0  2018  16496  41713
1  2019  19403  44115
2  2020  18240  43300
3  2021  20734  48000

In [ ]:
df_population

   Year  Korea_Pop  US_Pop
0  2018       51.6     327
1  2019       51.8     329
2  2020       51.7     331
3  2021       51.6     333

## (2) DataFrame 구조 이해하기

- 여러 도메인(금융, 의료, 과학, 스포츠, 여행 콘텐츠 등)의 데이터를 사용하여 pandas로 데이터 프레임을 다룰 수 있다.

| 컬럼명               | 설명                                                |
|----------------------|-----------------------------------------------------|
| loan_id              | 대출을 구분하는 고유 ID                             |
| married_or_not       | 신청자의 결혼 여부 (Y: 기혼, N: 미혼)               |
| self_employed_or_not | 자영업 여부 (Y: 자영업, N: 비자영업)                |
| applicant_income     | 신청자의 월 소득        |
| loan_amount          | 대출 금액   |
| property_area        | 주택/부동산 위치 (예: Rural, City 등)               |
| loan_status          | 대출 승인 여부 (Y: 승인, N: 거절)                   |

In [ ]:
# 데이터 불러오기
loan_df = pd.read_csv("loan.csv")
loan_df.head()

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y

### (a) 데이터 파악하기

- `head()`: 데이터 프레임의 상위 n개 행을 출력(기본값 n=5)

In [ ]:
loan_df.head()

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y

- `tail()`: 데이터 프레임의 하위 n개 행을 출력(기본값 n=5)

In [ ]:
loan_df.tail()

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

- `shape`: 데이터 프레임의 행과 열 개수를 튜플 형태로 반환 (예: `(행 개수, 열 개수)`)

In [ ]:
loan_df.shape  # 600개 행과 7개 열

(600, 7)

- `dtypes`: 데이터프레임 안 각 컬럼의 자료형(데이터 타입) 확인하기

In [ ]:
loan_df.dtypes

loan_id                  object
married_or_not           object
self_employed_or_not     object
applicant_income          int64
loan_amount             float64
property_area            object
loan_status              object
dtype: object

- `info()`: 데이터 프레임의 행과 열 개수, 컬럼 정보, 데이터 타입, 결측치 여부 등을 출력하여 데이터 구조를 빠르게 파악할 때 유용

In [ ]:
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   loan_id               600 non-null    object
 1   married_or_not        600 non-null    object
 2   self_employed_or_not  568 non-null    object
 3   applicant_income      600 non-null    int64
 4   loan_amount           589 non-null    float64
 5   property_area         600 non-null    object
 6   loan_status           600 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 32.9+ KB

- `describe()`: 수치형 데이터의 기술 통계(예. 평균, 중앙값, 최솟값, 최댓값, 사분위수, 표준편차 등) 확인하기

In [ ]:
loan_df.describe()

       applicant_income  loan_amount
count        600.000000   589.000000
mean        5412.161667   146.971307
std         6160.362669    85.756442
min          150.000000     9.200000
25%         2880.500000   100.700000
50%         3806.000000   128.000000
75%         5785.000000   168.300000
max        81000.000000   700.300000

- `describe(include='all')`: 문자형 데이터까지 포함하여 최빈값을 포함한 기술 통계량 확인하기
  - `unique`은 범주의 개수, `top`은 최빈값, `freq`은 최빈값이 등장하는 개수

In [ ]:
loan_df.describe(include='all')

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
count,600,600,568,600.000000,589.000000,600,600
unique,600,2,2,NaN,NaN,3,2
top,LP2990,Y,N,NaN,NaN,Suburb,Y
freq,1,390,488,NaN,NaN,228,408
mean,NaN,NaN,NaN,5412.161667,146.971307,NaN,NaN
std,NaN,NaN,NaN,6160.362669,85.756442,NaN,NaN
min,NaN,NaN,NaN,150.000000,9.200000,NaN,NaN
25%,NaN,NaN,NaN,2880.500000,100.700000,NaN,NaN
50%,NaN,NaN,NaN,3806.000000,128.000000,NaN,NaN
75%,NaN,NaN,NaN,5785.000000,168.300000,NaN,NaN
max,NaN,NaN,NaN,81000.000000,700.300000,NaN,NaN

- `sort_values()`: 정렬
  - `ascending=True`: 오름차순(기본값)
  - `ascending=False`: 내림차순

In [ ]:
loan_df.sort_values(by='loan_amount')

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
555,LP2840,N,N,2378,9.2,City,N
13,LP1030,Y,N,1299,17.5,City,Y
91,LP1325,N,N,3620,25.0,Suburb,Y
125,LP1482,Y,Y,3459,25.3,Suburb,Y
542,LP2792,Y,N,5468,26.5,Suburb,Y
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

In [ ]:
loan_df.sort_values(by='loan_amount', ascending=False)

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
163,LP1585,Y,N,51763,700.3,City,Y
122,LP1469,N,Y,20166,650.2,City,Y
548,LP2813,Y,Y,19484,600.4,Suburb,Y
147,LP1536,Y,N,39999,600.0,Suburb,Y
359,LP2191,Y,N,19730,570.1,Rural,N
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

### (b) 인덱스와 컬럼 구조 이해하기

(인덱스 설정하기)

In [ ]:
df = pd.read_excel("loan.xlsx", sheet_name=1, header=3, usecols=range(1, 8))
df.head()

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y

In [ ]:
df['loan_id'].count()

np.int64(600)

In [ ]:
df['loan_id'].nunique() #중복값 빼고

600

In [ ]:
df['loan_id'].isnull().sum() #결측값 개수

np.int64(0)

- `set_index()` : 데이터 프레임의 특정 컬럼을 행 인덱스로 설정하여 데이터 조회와 탐색을 직관적으로 하기 위하여 자주 사용하고, 주로 고유한 식별자가 있을 때 사용한다.

- `inplace=True`: 원본에 바로 적용 가능

In [ ]:
df = df.set_index('loan_id')

In [ ]:
df.set_index('loan_id', inplace=True) #원본에 반영

In [ ]:
df

,married,self_employed,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.0,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.0,City,Y
LP1008,N,N,6000,141.0,City,Y
LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.0,Rural,Y
LP2979,Y,N,4106,40.0,Rural,Y
LP2983,Y,N,8072,253.0,City,Y
LP2984,Y,N,7583,187.0,City,Y
LP2990,N,Y,4583,133.0,Suburb,N

- `reset_index()`: 설정한 인덱스를 해제하고 싶은 경우에 사용

In [ ]:
# df = df.reset_index()
df.reset_index(inplace=True)

In [ ]:
df

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.0,Rural,Y
596,LP2979,Y,N,4106,40.0,Rural,Y
597,LP2983,Y,N,8072,253.0,City,Y
598,LP2984,Y,N,7583,187.0,City,Y
599,LP2990,N,Y,4583,133.0,Suburb,N

(컬럼명 설정하기)

In [ ]:
df.head()

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y

In [ ]:
df.columns

Index(['loan_id', 'married', 'self_employed', 'applicant_income',
       'loan_amount', 'property_area', 'loan_status'],
      dtype='object')

In [ ]:
# 예시
# married -> married_or_not
# self_employed -> self_employed_or_not

In [ ]:
# 방법1.
df.columns = ['loan_id', 'married_or_not', 'self_employed_or_not', 'applicant_income',
              'loan_amount', 'property_area', 'loan_status']

In [ ]:
df.head()

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y

In [ ]:
# 예시
# married_or_not -> married
# self_employed_or_not -> self_employed
# applicant_income -> income
# loan_amount -> amount

In [ ]:
# 방법2. rename
new_columns = {'married_or_not':'married',
               'self_employed_or_not':'self_employed',
               'applicant_income':'income',
               'loan_amount':'amount'}

In [ ]:
# df = df.rename(columns=new_columns)
df.rename(columns=new_columns, inplace=True)

In [ ]:
df.head()

  loan_id married self_employed  income  amount property_area loan_status
0  LP1003       Y             N    4583   128.0         Rural           N
1  LP1005       Y             Y    3000    66.0          City           Y
2  LP1006       Y             N    2583   120.0          City           Y
3  LP1008       N             N    6000   141.0          City           Y
4  LP1011       Y             Y    5417   267.0          City           Y

### (c) 데이터 타입 다루기

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   loan_id        600 non-null    object
 1   married        600 non-null    object
 2   self_employed  568 non-null    object
 3   income         600 non-null    int64
 4   amount         589 non-null    float64
 5   property_area  600 non-null    object
 6   loan_status    600 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 32.9+ KB

In [ ]:
df.dtypes

loan_id           object
married           object
self_employed     object
income             int64
amount           float64
property_area     object
loan_status       object
dtype: object

In [ ]:
# income : 정수형 -> 실수형
df['income'] = df['income'].astype(float)

In [ ]:
df['income'].dtype

dtype('float64')

In [ ]:
# income : 실수형 -> 정수형
df['income'] = df['income'].astype(int)

In [ ]:
df['income'].dtype

dtype('int64')

In [ ]:
# income : 정수형 -> 문자형
df['income'] = df['income'].astype(str)

In [ ]:
df['income'].dtype  # Object

dtype('O')

### (d) DataFrame과 Series 구조 차이

- `Series` : 1차원 데이터 구조(하나의 열)
- `DataFrame` : 여러 Series가 모인 2차원 표 구조
- DataFrame에서 열 하나를 선택하면 Series가 된다.

In [ ]:
df.head()

  loan_id married self_employed income  amount property_area loan_status
0  LP1003       Y             N   4583   128.0         Rural           N
1  LP1005       Y             Y   3000    66.0          City           Y
2  LP1006       Y             N   2583   120.0          City           Y
3  LP1008       N             N   6000   141.0          City           Y
4  LP1011       Y             Y   5417   267.0          City           Y

In [ ]:
df.set_index('loan_id', inplace=True)

In [ ]:
df.head()

        married self_employed income  amount property_area loan_status
loan_id
LP1003        Y             N   4583   128.0         Rural           N
LP1005        Y             Y   3000    66.0          City           Y
LP1006        Y             N   2583   120.0          City           Y
LP1008        N             N   6000   141.0          City           Y
LP1011        Y             Y   5417   267.0          City           Y

In [ ]:
df['amount']

loan_id
LP1003    128.0
LP1005     66.0
LP1006    120.0
LP1008    141.0
LP1011    267.0
          ...
LP2974    108.0
LP2979     40.0
LP2983    253.0
LP2984    187.0
LP2990    133.0
Name: amount, Length: 600, dtype: float64

In [ ]:
type(df['amount'])

pandas.core.series.Series

- Series는 1차원 배열(array)과 비슷하지만, (1) 인덱스와 (2) 더 다양한 데이터 타입 지원이라는 차이가 있다.

In [ ]:
gdp_korea = pd.Series([12257, 11561, 13165, 14673, 16496, 19403],
                      index=[2015, 2016, 2017, 2018, 2019, 2020])
gdp_korea

2015    12257
2016    11561
2017    13165
2018    14673
2019    16496
2020    19403
dtype: int64

In [ ]:
# 인덱스로 값을 가져오기
gdp_korea[2019]

np.int64(16496)

### (e) 문자열 처리 기초

In [ ]:
df.head()

        married self_employed income  amount property_area loan_status
loan_id
LP1003        Y             N   4583   128.0         Rural           N
LP1005        Y             Y   3000    66.0          City           Y
LP1006        Y             N   2583   120.0          City           Y
LP1008        N             N   6000   141.0          City           Y
LP1011        Y             Y   5417   267.0          City           Y

- `unique()`: 범주의 종류

In [ ]:
df['self_employed'].unique()

array(['N', 'Y', nan], dtype=object)

- `nunique()`: 범주의 종류의 개수

In [ ]:
df['self_employed'].nunique()

2

In [ ]:
help(pd.DataFrame.value_counts())

TypeError: DataFrame.value_counts() missing 1 required positional argument: 'self'

- `value_counts()`: 범주별 도수
  - `dropna=True`: 결측값 제외(기본값)
  - `dropna=False`: 결측값 포함
  - `normalize=True` : 범주별 비율

In [ ]:
df['self_employed'].value_counts()

self_employed
N    488
Y     80
Name: count, dtype: int64

In [ ]:
df['self_employed'].value_counts(dropna=False)

self_employed
N      488
Y       80
NaN     32
Name: count, dtype: int64

In [ ]:
df['self_employed'].value_counts(normalize=True)

self_employed
N    0.859155
Y    0.140845
Name: proportion, dtype: float64

In [ ]:
df['self_employed'].value_counts(dropna=False, normalize=True)

self_employed
N      0.813333
Y      0.133333
NaN    0.053333
Name: proportion, dtype: float64

## (3) DataFrame 다루기

### (a) 데이터 선택(loc, iloc, 대괄호)

**데이터 선택 방법**

1. `iloc` (integer location): 행/열 **번호**로 접근하여 정수 기반 인덱스를 사용해 데이터 선택
2. `loc` (location): 행/열 **이름**으로 접근하여 레이블(이름) 기반 인덱스를 사용해 데이터 선택
3. 대괄호(`[]`) 사용
    - 열 선택: `df['column1']` → `'column1'` 열 반환  
    - 여러 열 선택: `df[['column1', 'column2']]` → 두 개 이상의 열 반환  
    - 행 슬라이싱: `df[0:3]` → 0~2번째 행 반환 (정수 위치 기준)

In [ ]:
burger_df = pd.read_csv("burger.csv", index_col=0)
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     NaN  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

(방법1 : iloc 사용)

In [ ]:
burger_df.iloc[3, 1]

np.int64(50)

In [ ]:
burger_df.iloc[[2, 3], [1, 2]]

                       carb  protein
product_name
Double Whopper           49       48
Double Cheese Whopper    50       52

(방법2 : loc 사용)

In [ ]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     NaN  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [ ]:
burger_df.loc['Double Whopper', 'protein']

np.int64(48)

In [ ]:
burger_df.loc[['Whopper', 'Double Whopper'], ['carb', 'protein', 'fat']]

                carb  protein  fat
product_name
Whopper           49       28   40
Double Whopper    49       48   58

(방법3 : 대괄호 사용)

In [ ]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     NaN  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [ ]:
burger_df[['calories', 'fat']]

                       calories  fat
product_name
Whopper                     660   40
Cheese Whopper              740   46
Double Whopper              900   58
Double Cheese Whopper       980   64
Whopper Junior              310   18
Bacon King                 1150   79
Single Stacker King         700   42
Double Stacker King        1050   68
Hamburger                   240   10
Cheeseburger                280   13
Double Hamburger            350   18
Double Cheeseburger         390   21
Crispy Chicken              670   41
Chicken Nuggets             170   11
Spicy Chicken Nuggets       210   15

### (b) 조건 필터링(불린 인덱싱, query)

In [ ]:
# 데이터 불러오기
burger_df = pd.read_csv("burger.csv", index_col="product_name")

In [ ]:
burger_df.head()

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers

In [ ]:
burger_df['calories'] < 500

product_name
Whopper                  False
Cheese Whopper           False
Double Whopper           False
Double Cheese Whopper    False
Whopper Junior            True
Bacon King               False
Single Stacker King      False
Double Stacker King      False
Hamburger                 True
Cheeseburger              True
Double Hamburger          True
Double Cheeseburger       True
Crispy Chicken           False
Chicken Nuggets           True
Spicy Chicken Nuggets     True
Name: calories, dtype: bool

In [ ]:
condition = burger_df['calories'] < 500
burger_df[condition]

                       calories  carb  protein  fat  sodium category
product_name
Whopper Junior              310    27       13   18     0.4  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [ ]:
condition = burger_df['calories'] < 500
burger_df.loc[condition, :]

                       calories  carb  protein  fat  sodium category
product_name
Whopper Junior              310    27       13   18     0.4  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [ ]:
condition = burger_df['calories'] < 500
burger_df.loc[condition, 'protein']

product_name
Whopper Junior           13
Hamburger                13
Cheeseburger             15
Double Hamburger         21
Double Cheeseburger      23
Chicken Nuggets           8
Spicy Chicken Nuggets     8
Name: protein, dtype: int64

In [ ]:
condition = burger_df['calories'] < 500
burger_df.loc[condition, ['calories', 'protein']]

                       calories  protein
product_name
Whopper Junior              310       13
Hamburger                   240       13
Cheeseburger                280       15
Double Hamburger            350       21
Double Cheeseburger         390       23
Chicken Nuggets             170        8
Spicy Chicken Nuggets       210        8

- `query()`: DataFrame에서 조건식을 문자열로 작성해 행을 필터링

**작성**

- `df.query('조건식')`

**기능**

- 문자열 조건식을 사용해 행(row)을 필터링
- 불린 인덱싱보다 코드가 짧고 가독성이 좋음
- 여러 조건 결합 시 가독성이 특히 좋음

**@: 변수 참조 연산자**

- `@`: `query()` 안에서 외부 변수를 참조하는 기호

In [ ]:
# 데이터 불러오기
df = pd.read_csv("loan.csv", index_col="loan_id")

In [ ]:
df.head()

,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.4,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.5,City,Y
LP1008,N,N,6000,141.4,City,Y
LP1011,Y,Y,5417,267.4,City,Y

In [ ]:
new_columns = {'married_or_not':'married',
               'self_employed_or_not':'self_employed',
               'applicant_income':'income',
               'loan_amount':'amount'}

df.rename(columns=new_columns, inplace=True)

In [ ]:
df['income'] = df['income'].astype(int)

(예시1) income이 5000 보다 큰 경우

In [ ]:
df.query("income > 5000")

        married self_employed  income  amount property_area loan_status
loan_id
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1020        Y             N   12841   349.3        Suburb           N
LP1043        Y             N    7660   104.1          City           N
LP1046        Y             N    5955   315.5          City           Y
...         ...           ...     ...     ...           ...         ...
LP2948        Y             N    5780   192.9          City           Y
LP2953        Y             N    5703   128.5          City           Y
LP2959        Y             N   12000   497.0        Suburb           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[187 rows x 6 columns]

(예시2) income이 평균보다 큰 경우

In [ ]:
income_mean = df['income'].mean()
income_mean

np.float64(5412.161666666667)

In [ ]:
df.query("income > @income_mean")

        married self_employed  income  amount property_area loan_status
loan_id
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1020        Y             N   12841   349.3        Suburb           N
LP1043        Y             N    7660   104.1          City           N
LP1046        Y             N    5955   315.5          City           Y
...         ...           ...     ...     ...           ...         ...
LP2948        Y             N    5780   192.9          City           Y
LP2953        Y             N    5703   128.5          City           Y
LP2959        Y             N   12000   497.0        Suburb           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[172 rows x 6 columns]

(예시3) 부동산 타입이 도시인 경우

In [ ]:
df.query("property_area == 'City'")

        married self_employed  income  amount property_area loan_status
loan_id
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1013        Y             N    2333    95.3          City           Y
...         ...           ...     ...     ...           ...         ...
LP2949        N           NaN     416   350.6          City           N
LP2953        Y             N    5703   128.5          City           Y
LP2960        Y             N    2400     NaN          City           N
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[197 rows x 6 columns]

(예시4) 부동산 타입이 도시 또는 교외인 경우

In [ ]:
df.query("property_area in ('City', 'Suburb')")

        married self_employed  income  amount property_area loan_status
loan_id
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1013        Y             N    2333    95.3          City           Y
...         ...           ...     ...     ...           ...         ...
LP2960        Y             N    2400     NaN          City           N
LP2961        Y             N    3400   174.0        Suburb           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[425 rows x 6 columns]

(예시5) 부동산 타입이 도시 또는 교외가 아닌 경우

In [ ]:
df.query("property_area not in ('City', 'Suburb')")

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1029        N             N    1853   114.1         Rural           N
LP1038        Y             N    4887   133.5         Rural           N
LP1050        Y             N    3365   112.4         Rural           N
LP1097        N             Y    4692   106.2         Rural           N
...         ...           ...     ...     ...           ...         ...
LP2950        Y           NaN    2894   155.5         Rural           Y
LP2958        N             N    3676   172.3         Rural           Y
LP2964        Y             N    3987   157.3         Rural           Y
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y

[175 rows x 6 columns]

(예시6) 결혼을 했고, 수입이 평균보다 큰 경우

In [ ]:
df.query("(married == 'Y') & (income > @income_mean)")

        married self_employed  income  amount property_area loan_status
loan_id
LP1011        Y             Y    5417   267.4          City           Y
LP1020        Y             N   12841   349.3        Suburb           N
LP1043        Y             N    7660   104.1          City           N
LP1046        Y             N    5955   315.5          City           Y
LP1066        Y             Y    9560   191.1        Suburb           Y
...         ...           ...     ...     ...           ...         ...
LP2948        Y             N    5780   192.9          City           Y
LP2953        Y             N    5703   128.5          City           Y
LP2959        Y             N   12000   497.0        Suburb           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[120 rows x 6 columns]

(여러 조건으로 불린 인덱싱하기)

In [ ]:
# 데이터 불러오기
loan_df = pd.read_csv("loan.csv", index_col=0)
loan_df.head()

,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.4,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.5,City,Y
LP1008,N,N,6000,141.4,City,Y
LP1011,Y,Y,5417,267.4,City,Y

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 600 entries, LP1003 to LP2990
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   married        600 non-null    object
 1   self_employed  568 non-null    object
 2   income         600 non-null    int64
 3   amount         589 non-null    float64
 4   property_area  600 non-null    object
 5   loan_status    600 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 49.0+ KB

(예시1) 결혼을 했**고**, 수입이 평균보다 큰 경우

In [ ]:
# 결혼에 대한 조건
condition1 = (df['married'] == 'Y')

In [ ]:
# 수입에 대한 조건
condition2 = (df['income'] > df['income'].mean())

In [ ]:
df[condition1 & condition2]

        married self_employed  income  amount property_area loan_status
loan_id
LP1011        Y             Y    5417   267.4          City           Y
LP1020        Y             N   12841   349.3        Suburb           N
LP1043        Y             N    7660   104.1          City           N
LP1046        Y             N    5955   315.5          City           Y
LP1066        Y             Y    9560   191.1        Suburb           Y
...         ...           ...     ...     ...           ...         ...
LP2948        Y             N    5780   192.9          City           Y
LP2953        Y             N    5703   128.5          City           Y
LP2959        Y             N   12000   497.0        Suburb           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[120 rows x 6 columns]

(예시2) 결혼을 했**거나**, 수입이 평균보다 큰 경우

In [ ]:
df[condition1 | condition2]

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2964        Y             N    3987   157.3         Rural           Y
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[442 rows x 6 columns]

(예시3) 결혼을 했**거나**, 수입이 전체 평균보다 크**고**, 부동산이 도시에 있지 않은 경우

In [ ]:
# 결혼에 대한 조건
condition1 = (df['married'] == 'Y')

In [ ]:
# 수입에 대한 조건
condition2 = (df['income'] > df['income'].mean())

In [ ]:
# 부동산에 대한 조건
condition3 = (df['property_area'] == 'City')

In [ ]:
df[condition1 | condition2 & ~condition3]

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1013        Y             N    2333    95.3          City           Y
...         ...           ...     ...     ...           ...         ...
LP2964        Y             N    3987   157.3         Rural           Y
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[426 rows x 6 columns]

(예시3) 1) 결혼을 했거나 2) 수입이 전체 평균보다 크고, 부동산이 도시에 있지 않은 경우

In [ ]:
df[condition1 | (condition2 & ~condition3)]

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1013        Y             N    2333    95.3          City           Y
...         ...           ...     ...     ...           ...         ...
LP2964        Y             N    3987   157.3         Rural           Y
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[426 rows x 6 columns]

(예시4) 부동산이 도시 또는 교외인 경우

In [ ]:
df[df['property_area'].isin(['City', 'Suburb'])]

        married self_employed  income  amount property_area loan_status
loan_id
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1013        Y             N    2333    95.3          City           Y
...         ...           ...     ...     ...           ...         ...
LP2960        Y             N    2400     NaN          City           N
LP2961        Y             N    3400   174.0        Suburb           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[425 rows x 6 columns]

### (c) 데이터 수정 및 추가

- 특정 행/열의 값 변경하기
- 특정 행의 값 변경하기
- 특정 열의 값 변경하기
- 특정 행에 값 추가하기
- 특정 열에 값 일괄 추가하기
- 조건에 따라 값 추가하기

In [ ]:
burger_df = pd.read_csv("burger.csv", index_col="product_name")
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     NaN  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

(6-1) 특정 행·열의 값 변경하기

In [ ]:
burger_df.loc['Double Stacker King', 'sodium']

np.float64(nan)

In [ ]:
burger_df.loc['Double Stacker King', 'sodium'] = 1.9

In [ ]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     1.9  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

(6-2) 특정 행의 값 변경하기

In [ ]:
burger_df.loc['Cheeseburger']

calories        280
carb             27
protein          15
fat              13
sodium          0.6
category    Burgers
Name: Cheeseburger, dtype: object

In [ ]:
burger_df.loc['Cheeseburger'] = [360, 24, 18, 21, 0.7, 'Burgers']

In [ ]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     1.9  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                360    24       18   21     0.7  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

(6-3) 특정 열의 값 변경하기

In [ ]:
burger_df['sodium']

product_name
Whopper                  1.0
Cheese Whopper           1.3
Double Whopper           1.0
Double Cheese Whopper    1.4
Whopper Junior           0.4
Bacon King               2.2
Single Stacker King      1.4
Double Stacker King      1.9
Hamburger                0.4
Cheeseburger             0.7
Double Hamburger         0.4
Double Cheeseburger      0.6
Crispy Chicken           1.1
Chicken Nuggets          0.3
Spicy Chicken Nuggets    0.6
Name: sodium, dtype: float64

In [ ]:
burger_df['sodium'] = [1.8, 1.6, 1.3, 2.2, 0.9, 2.4, 1.7, 2.2, 0.8, 1.1, 0.7, 1.2, 1.5, 0.8, 1.3]

In [ ]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.8  Burgers
Cheese Whopper              740    50       32   46     1.6  Burgers
Double Whopper              900    49       48   58     1.3  Burgers
Double Cheese Whopper       980    50       52   64     2.2  Burgers
Whopper Junior              310    27       13   18     0.9  Burgers
Bacon King                 1150    49       61   79     2.4  Burgers
Single Stacker King         700    48       35   42     1.7  Burgers
Double Stacker King        1050    49       61   68     2.2  Burgers
Hamburger                   240    26       13   10     0.8  Burgers
Cheeseburger                360    24       18   21     1.1  Burgers
Double Hamburger            350    26       21   18     0.7  Burgers
Double Cheeseburger         390    27       23   21     1.2  Burgers
Crispy Chicken              670    54       23   41     1.5  Chicken
Chicken Nuggets             170    11        8   11     0.8  Chicken
Spicy Chicken Nuggets       210    11        8   15     1.3  Chicken

(6-4) 특정 행에 값 추가하기

In [ ]:
burger_df.loc['Tripple Whopper'] = [1130, 49, 67, 75, 1.1, 'Burgers']

In [ ]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.8  Burgers
Cheese Whopper              740    50       32   46     1.6  Burgers
Double Whopper              900    49       48   58     1.3  Burgers
Double Cheese Whopper       980    50       52   64     2.2  Burgers
Whopper Junior              310    27       13   18     0.9  Burgers
Bacon King                 1150    49       61   79     2.4  Burgers
Single Stacker King         700    48       35   42     1.7  Burgers
Double Stacker King        1050    49       61   68     2.2  Burgers
Hamburger                   240    26       13   10     0.8  Burgers
Cheeseburger                360    24       18   21     1.1  Burgers
Double Hamburger            350    26       21   18     0.7  Burgers
Double Cheeseburger         390    27       23   21     1.2  Burgers
Crispy Chicken              670    54       23   41     1.5  Chicken
Chicken Nuggets             170    11        8   11     0.8  Chicken
Spicy Chicken Nuggets       210    11        8   15     1.3  Chicken
Tripple Whopper            1130    49       67   75     1.1  Burgers

(6-5) 특정 열에 값 일괄 추가하기

In [ ]:
burger_df['brand'] = 'Burger King'

In [ ]:
burger_df

,calories,carb,protein,fat,sodium,category,brand
product_name,,,,,,,
Whopper,660,49,28,40,1.8,Burgers,Burger King
Cheese Whopper,740,50,32,46,1.6,Burgers,Burger King
Double Whopper,900,49,48,58,1.3,Burgers,Burger King
Double Cheese Whopper,980,50,52,64,2.2,Burgers,Burger King
Whopper Junior,310,27,13,18,0.9,Burgers,Burger King
Bacon King,1150,49,61,79,2.4,Burgers,Burger King
Single Stacker King,700,48,35,42,1.7,Burgers,Burger King
Double Stacker King,1050,49,61,68,2.2,Burgers,Burger King
Hamburger,240,26,13,10,0.8,Burgers,Burger King
Cheeseburger,360,24,18,21,1.1,Burgers,Burger King
Double Hamburger,350,26,21,18,0.7,Burgers,Burger King
Double Cheeseburger,390,27,23,21,1.2,Burgers,Burger King
Crispy Chicken,670,54,23,41,1.5,Chicken,Burger King
Chicken Nuggets,170,11,8,11,0.8,Chicken,Burger King
Spicy Chicken Nuggets,210,11,8,15,1.3,Chicken,Burger King
Tripple Whopper,1130,49,67,75,1.1,Burgers,Burger King

(6-6) 조건에 따라 값 추가하기

- data.loc[`조건`, `새 컬럼명`] = `추가할 데이터`

In [ ]:
burger_df.loc[burger_df['calories'] >= 500, 'high_calories'] = True
burger_df.loc[burger_df['calories'] < 500, 'high_calories'] = False

In [ ]:
burger_df

,calories,carb,protein,fat,sodium,category,brand,high_calories
product_name,,,,,,,,
Whopper,660,49,28,40,1.8,Burgers,Burger King,True
Cheese Whopper,740,50,32,46,1.6,Burgers,Burger King,True
Double Whopper,900,49,48,58,1.3,Burgers,Burger King,True
Double Cheese Whopper,980,50,52,64,2.2,Burgers,Burger King,True
Whopper Junior,310,27,13,18,0.9,Burgers,Burger King,False
Bacon King,1150,49,61,79,2.4,Burgers,Burger King,True
Single Stacker King,700,48,35,42,1.7,Burgers,Burger King,True
Double Stacker King,1050,49,61,68,2.2,Burgers,Burger King,True
Hamburger,240,26,13,10,0.8,Burgers,Burger King,False
Cheeseburger,360,24,18,21,1.1,Burgers,Burger King,False
Double Hamburger,350,26,21,18,0.7,Burgers,Burger King,False
Double Cheeseburger,390,27,23,21,1.2,Burgers,Burger King,False
Crispy Chicken,670,54,23,41,1.5,Chicken,Burger King,True
Chicken Nuggets,170,11,8,11,0.8,Chicken,Burger King,False
Spicy Chicken Nuggets,210,11,8,15,1.3,Chicken,Burger King,False
Tripple Whopper,1130,49,67,75,1.1,Burgers,Burger King,True

### (d) 데이터 삭제

**drop()함수와 axis**

- `drop()`: DataFrame에서 특정 행(row)이나 열(column)을 제거

**기본 개념**

- 지정한 라벨(label: 행 인덱스나 열 이름)을 기준으로 데이터를 제거하는데, 행/열 중 어디를 삭제할지 `axis`로 지정 가능
  - `axis=0`: 행(row) 삭제(기본값)
  - `axis=1`: 열(column) 삭제

(예시1: drop()과 axis 이해하기)

In [ ]:
loan_df = pd.read_csv("loan.csv")
loan_df.head()

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y

- 열 삭제 시 drop() 안에 columns 나 axis=1을 지정한다.

In [ ]:
loan_df.drop(columns='married_or_not')

,loan_id,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,N,4583,128.4,Rural,N
1,LP1005,Y,3000,66.0,City,Y
2,LP1006,N,2583,120.5,City,Y
3,LP1008,N,6000,141.4,City,Y
4,LP1011,Y,5417,267.4,City,Y
...,...,...,...,...,...,...
595,LP2974,N,3232,108.6,Rural,Y
596,LP2979,N,4106,40.7,Rural,Y
597,LP2983,N,8072,253.4,City,Y
598,LP2984,N,7583,187.6,City,Y
599,LP2990,Y,4583,133.2,Suburb,N

In [ ]:
loan_df.drop('married_or_not', axis=1)

,loan_id,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,N,4583,128.4,Rural,N
1,LP1005,Y,3000,66.0,City,Y
2,LP1006,N,2583,120.5,City,Y
3,LP1008,N,6000,141.4,City,Y
4,LP1011,Y,5417,267.4,City,Y
...,...,...,...,...,...,...
595,LP2974,N,3232,108.6,Rural,Y
596,LP2979,N,4106,40.7,Rural,Y
597,LP2983,N,8072,253.4,City,Y
598,LP2984,N,7583,187.6,City,Y
599,LP2990,Y,4583,133.2,Suburb,N

(예시2: 행 삭제)

In [ ]:
df.head()

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y

In [ ]:
# LP1006 대출 아이디가 있는 행 삭제
df.drop('LP1006', inplace=True)

In [ ]:
df.head()

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
LP1013        Y             N    2333    95.3          City           Y

(예시3: 열 삭제)

In [ ]:
df.drop(columns='married', inplace=True)

In [ ]:
# df.drop('married', axis=1)

In [ ]:
df.head()

        self_employed  income  amount property_area loan_status
loan_id
LP1003              N    4583   128.4         Rural           N
LP1005              Y    3000    66.0          City           Y
LP1008              N    6000   141.4          City           Y
LP1011              Y    5417   267.4          City           Y
LP1013              N    2333    95.3          City           Y

(예시4: 여러 개 열 삭제하기)

In [ ]:
cols = ['income', 'amount']
df.drop(columns=cols)

        self_employed property_area loan_status
loan_id
LP1003              N         Rural           N
LP1005              Y          City           Y
LP1008              N          City           Y
LP1011              Y          City           Y
LP1013              N          City           Y
...               ...           ...         ...
LP2974              N         Rural           Y
LP2979              N         Rural           Y
LP2983              N          City           Y
LP2984              N          City           Y
LP2990              Y        Suburb           N

[599 rows x 3 columns]

In [ ]:
#df.drop(columns=['income', 'amount'])

## (4) 데이터 전처리 : 품질 관리

### (a) 결측값 처리

(결측값 확인하기)

- GIGO(Garbage In, Garbage Out)

| 컬럼명         | 설명                                   |
|----------------|----------------------------------------|
| id             | 숙소 고유 식별자 ID                    |
| state          | 숙소가 위치한 주                |
| guests         | 수용 가능한 게스트(투숙객) 수          |
| beds           | 제공되는 침대 수                       |
| property_type  | 숙소 유형(예: Apartment, House 등)    |
| rating         | 숙소 평점(0~100, NaN은 평점 없음)     |
| n_reviews      | 리뷰 개수                              |
| location       | 상세 위치(도시, 지역)                 |
| price          | 1박 숙박 요금(통화 단위는 상황에 따라)|

In [ ]:
# 데이터 불러오기
airbnb_df = pd.read_csv("airbnb.csv")

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64

In [ ]:
airbnb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             713 non-null    object
 1   state          713 non-null    object
 2   guests         713 non-null    int64
 3   beds           713 non-null    int64
 4   property_type  713 non-null    object
 5   rating         700 non-null    float64
 6   n_reviews      713 non-null    int64
 7   location       713 non-null    object
 8   price          713 non-null    int64
dtypes: float64(1), int64(4), object(4)
memory usage: 50.3+ KB

- `isna()`, `isnull()`: 결측치 확인 시 사용

In [ ]:
# 전체 결측치 개수
airbnb_df.isna().sum().sum()

np.int64(13)

In [ ]:
# 컬럼별 결측치 개수
airbnb_df.isna().sum()

id                0
state             0
guests            0
beds              0
property_type     0
rating           13
n_reviews         0
location          0
price             0
dtype: int64

(결측값 처리하기)

- `dropna()`: 결측치 삭제하기
- `fillna()`: 결측치 대체하기
- `notna()` : 결측치가 아닌 데이터만 확인할 때 사용

In [ ]:
airbnb_df.shape

(713, 9)

In [ ]:
airbnb_df[airbnb_df['rating'].notna()]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
5,PP4626,California,2,1,Apartment,92.0,211,"Western Addition/NOPA, San Francisco.",129
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

(결측치 삭제하기)

In [ ]:
airbnb_df.dropna()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
5,PP4626,California,2,1,Apartment,92.0,211,"Western Addition/NOPA, San Francisco.",129
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [ ]:
airbnb_df.dropna().shape

(700, 9)

(결측치 대체하기)

In [ ]:
airbnb_df.isna().sum()

id                0
state             0
guests            0
beds              0
property_type     0
rating           13
n_reviews         0
location          0
price             0
dtype: int64

In [ ]:
rating_mean = airbnb_df['rating'].mean()
rating_mean

np.float64(94.82)

In [ ]:
airbnb_df['rating'] = airbnb_df['rating'].fillna(rating_mean)

In [ ]:
# 결측치 확인하기
airbnb_df.isna().sum()

id               0
state            0
guests           0
beds             0
property_type    0
rating           0
n_reviews        0
location         0
price            0
dtype: int64

### (b) 중복값 처리

- 중복값 : 중복되어 있는 값

(중복값 확인하기)

- 중복값이 있는지 확인할 때에는 `describe()`을 사용해서 `count()` 개수와 `unique()` 개수에 차이가 있는지 비교할 수도 있고, `duplicated()`를 사용하면 쉽게 확인할 수 있다.

| 옵션           | 설명                                                                 | 기본값 |
|----------------|----------------------------------------------------------------------|--------|
| subset         | 중복 여부를 확인할 **특정 컬럼** 지정 가능 (리스트 형태도 가능)        | None (전체 컬럼 기준) |
| keep           | 중복된 값 중 어떤 것을 True로 표시할지 결정                           | 'first' |
| ㆍ 'first'     | 처음 등장한 행은 남기고, 이후 중복된 행을 True로 표시                 |        |
| ㆍ 'last'      | 마지막 등장한 행은 남기고, 이전 중복된 행을 True로 표시               |        |
| ㆍ False       | 중복된 모든 행을 True로 표시                                          |        |
| inplace        | DataFrame에 바로 적용할지 여부 (실제 `drop_duplicates()`에서 주로 사용) | False  |

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.00,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,94.82,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.00,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.00,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.00,23,"West Roxbury, Boston.",64

In [ ]:
airbnb_df.shape

(713, 9)

(예시1: 모든 컬럼에 대하여 중복 여부 확인하기)

- `.duplicated().sum()`을 사용하면 중복이 있는 행의 수를 출력할 수 있다.

In [ ]:
airbnb_df.duplicated().sum()

np.int64(2)

- `duplicated()`를 사용하면 중복이 있는지 없는지 여부가 불린으로 출력된다.

In [ ]:
airbnb_df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
708    False
709    False
710    False
711    False
712    False
Length: 713, dtype: bool

In [ ]:
airbnb_df[airbnb_df.duplicated(keep=False)]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
201,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124

(예시2: 특정 컬럼에 대하여 중복 여부 확인하기)

In [ ]:
airbnb_df.duplicated(subset='id').sum()

np.int64(6)

In [ ]:
airbnb_df[airbnb_df.duplicated(subset='id', keep=False)].sort_values(by='id')

,id,state,guests,beds,property_type,rating,n_reviews,location,price
541,BZ3596,Illinois,2,1,Apartment,91.0,28,"Lakeview, Chicago.",119
601,BZ3596,Illinois,2,1,House,89.0,30,"Lakeview, Chicago.",119
6,LN3479,California,2,2,Apartment,96.0,15,"East Hollywood, Los Angeles.",88
448,LN3479,California,2,2,Apartment,98.0,19,"East Hollywood, Los Angeles.",88
452,LN3479,California,2,2,Apartment,99.0,25,"East Hollywood, Los Angeles.",91
273,QO8555,California,7,4,House,85.0,3,"Excelsior, San Francisco.",199
527,QO8555,California,7,4,House,80.0,1,"Excelsior, San Francisco.",199
201,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124

(중복값 처리하기)

`drop_duplicates()`: DataFrame에서 중복된 행을 제거
  - `keep='first'`(기본값): 중복된 행이 여러 개 있는 경우, 첫 번째만 남기고 나머지는 제거
  - `keep='last'`: 마지막 것만 남기고 앞의 중복 제거
  - `keep=False`: 중복된 모든 행 제거

In [ ]:
airbnb_df.shape

(713, 9)

In [ ]:
# 모든 컬럼에 대해 중복인 경우 중복값 제거
airbnb_df.drop_duplicates()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.00,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,94.82,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.00,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.00,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.00,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.00,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.00,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.00,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.00,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.00,61,"East Boston, Boston.",115

(예시1: id 컬럼에 대하여 중복값 처리하기)

In [ ]:
airbnb_df.drop_duplicates(subset='id')

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.00,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,94.82,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.00,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.00,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.00,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.00,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.00,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.00,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.00,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.00,61,"East Boston, Boston.",115

(예시2: id, price 컬럼에 대하여 중복값 처리하기)

In [ ]:
airbnb_df.duplicated(subset=['id', 'price']).sum()

np.int64(5)

In [ ]:
airbnb_df[airbnb_df.duplicated(subset=['id', 'price'], keep=False)].sort_values(by=['id', 'price'])

,id,state,guests,beds,property_type,rating,n_reviews,location,price
541,BZ3596,Illinois,2,1,Apartment,91.0,28,"Lakeview, Chicago.",119
601,BZ3596,Illinois,2,1,House,89.0,30,"Lakeview, Chicago.",119
6,LN3479,California,2,2,Apartment,96.0,15,"East Hollywood, Los Angeles.",88
448,LN3479,California,2,2,Apartment,98.0,19,"East Hollywood, Los Angeles.",88
273,QO8555,California,7,4,House,85.0,3,"Excelsior, San Francisco.",199
527,QO8555,California,7,4,House,80.0,1,"Excelsior, San Francisco.",199
201,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124

In [ ]:
airbnb_df.drop_duplicates(subset=['id', 'price'])

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.00,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,94.82,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.00,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.00,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.00,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.00,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.00,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.00,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.00,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.00,61,"East Boston, Boston.",115

### (c) 이상점 처리

- 이상점(outlier) : 다른 값들과 동떨어져 있는 너무 크거나 너무 작은 데이터

(이상점 확인하기)

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.00,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,94.82,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.00,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.00,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.00,23,"West Roxbury, Boston.",64

In [ ]:
airbnb_df.dtypes

id                object
state             object
guests             int64
beds               int64
property_type     object
rating           float64
n_reviews          int64
location          object
price              int64
dtype: object

- airbnb 데이터의 price 컬럼에 대하여 이상점 확인

In [ ]:
# IQR 기반 이상점 확인
q3 = airbnb_df['price'].quantile(0.75)
q1 = airbnb_df['price'].quantile(0.25)

iqr = q3 - q1

upper_limit = q3 + 1.5*iqr
lower_limit = q1 - 1.5*iqr

# 이상치
outlier = (airbnb_df['price'] < lower_limit) | (airbnb_df['price'] > upper_limit)
airbnb_df[outlier]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
13,HB7516,Illinois,1,1,Apartment,94.0,56,"Little Italy/UIC, Chicago.",14
43,IT4655,California,2,8,Hostel,91.0,27,"Westlake, Los Angeles.",14
91,FG7538,California,6,3,House,100.0,6,"Marina, San Francisco.",1800
442,ZL3688,California,16,8,Villa,92.0,7,"Malibu, Los Angeles.",1794

(이상점 처리하기)

1. 그대로 두기

  - 데이터의 특성을 잘 반영할 수도 있는 경우

2. 삭제하기

  - 데이터 입력 오류나 측정 실수로 발생한 경우
  - 해당 데이터를 삭제해도 전체 분석에 큰 영향이 없는 경우

3. 정상 범위로 조정하기

  - IQR 기반 정상 범위를 벗어나는 값은 정상 범위로 조정하여 별도 처리

In [ ]:
# 정상 범위
condition1 = (airbnb_df['price'] >= lower_limit)
condition2 = (airbnb_df['price'] <= upper_limit)

airbnb_df[condition1 & condition2]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.00,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,94.82,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.00,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.00,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.00,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.00,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.00,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.00,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.00,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.00,61,"East Boston, Boston.",115

In [ ]:
# 이상치
airbnb_df[outlier].shape

(4, 9)

In [ ]:
# 정상 범위
airbnb_df[condition1 & condition2].shape

(709, 9)

In [ ]:
# 전체 = 이상치 + 정상 범위
airbnb_df.shape

(713, 9)

## (5) 데이터 전처리 : 문자열 처리

### (a) 대소문자 처리하기


1. `.upper()`: 문자열의 모든 문자를 **대문자**로 변환
   - 예: `"python".upper()` → `"PYTHON"`

2. `.lower()`: 문자열의 모든 문자를 **소문자**로 변환  
   - 예: `"PyThOn".lower()` → `"python"`

3. `.capitalize()`: 문자열의 맨 앞 글자만 **대문자**로, 나머지는 소문자로 변환  
   - 예: `"pyTHon".capitalize()` → `"Python"`

In [ ]:
# 데이터 불러오기
airbnb_df = pd.read_csv('airbnb.csv')
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64

In [ ]:
airbnb_df['state'].unique()

array(['Illinois', 'MASSACHUSETTS', 'ILLINOIS', 'california',
       'massachusetts', 'California', 'Massachusetts', 'CALIFORNIA',
       'illinois'], dtype=object)

- `.upper()`: 문자열의 모든 문자를 대문자로 변환

In [ ]:
airbnb_df['state'].str.upper()

0           ILLINOIS
1      MASSACHUSETTS
2           ILLINOIS
3         CALIFORNIA
4      MASSACHUSETTS
           ...
708       CALIFORNIA
709       CALIFORNIA
710       CALIFORNIA
711         ILLINOIS
712    MASSACHUSETTS
Name: state, Length: 713, dtype: object

- `.lower()`: 문자열의 모든 문자를 소문자로 변환

In [ ]:
airbnb_df['state'].str.lower()

0           illinois
1      massachusetts
2           illinois
3         california
4      massachusetts
           ...
708       california
709       california
710       california
711         illinois
712    massachusetts
Name: state, Length: 713, dtype: object

- `.capitalize()`: 문자열의 맨 앞 글자만 대문자로, 나머지는 소문자로 변환

In [ ]:
airbnb_df['state'].str.capitalize()

0           Illinois
1      Massachusetts
2           Illinois
3         California
4      Massachusetts
           ...
708       California
709       California
710       California
711         Illinois
712    Massachusetts
Name: state, Length: 713, dtype: object

In [ ]:
airbnb_df['state'] = airbnb_df['state'].str.capitalize()

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,Illinois,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,California,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,Massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64

### (b) 문자열 분리하기

- `split()`: 문자열 분리

In [ ]:
airbnb_df['location'].str.split(',')

0               [Avondale,  Chicago.]
1               [South End,  Boston.]
2               [Avondale,  Chicago.]
3             [SoMa,  San Francisco.]
4            [West Roxbury,  Boston.]
                    ...
708           [Venice,  Los Angeles.]
709     [Mid-Wilshire,  Los Angeles.]
710    [Redondo Beach,  Los Angeles.]
711             [Lakeview,  Chicago.]
712           [East Boston,  Boston.]
Name: location, Length: 713, dtype: object

In [ ]:
airbnb_df['location'].str.split(',').str[0]

0           Avondale
1          South End
2           Avondale
3               SoMa
4       West Roxbury
           ...
708           Venice
709     Mid-Wilshire
710    Redondo Beach
711         Lakeview
712      East Boston
Name: location, Length: 713, dtype: object

In [ ]:
airbnb_df['location'].str.split(',').str[1]

0             Chicago.
1              Boston.
2             Chicago.
3       San Francisco.
4              Boston.
            ...
708       Los Angeles.
709       Los Angeles.
710       Los Angeles.
711           Chicago.
712            Boston.
Name: location, Length: 713, dtype: object

(location 열을 기반으로 neighborhood 열 생성하기)

In [ ]:
airbnb_df['neighborhood'] = airbnb_df['location'].str.split(',').str[0]

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,location,price,neighborhood
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48,Avondale
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,"South End, Boston.",115,South End
2,OZ5857,Illinois,4,3,Apartment,100.0,51,"Avondale, Chicago.",150,Avondale
3,HY8797,California,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125,SoMa
4,VN7858,Massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64,West Roxbury

(location 열을 기반으로 city 열 생성하기)

In [ ]:
airbnb_df['city'] = airbnb_df['location'].str.split(',').str[1]

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,location,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48,Avondale,Chicago.
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,"South End, Boston.",115,South End,Boston.
2,OZ5857,Illinois,4,3,Apartment,100.0,51,"Avondale, Chicago.",150,Avondale,Chicago.
3,HY8797,California,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125,SoMa,San Francisco.
4,VN7858,Massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64,West Roxbury,Boston.

(neighborhood 열과 city 열 생성한 후 location 열 삭제하기)

In [ ]:
#airbnb_df.drop(columns='location')

In [ ]:
airbnb_df.drop('location', axis=1, inplace=True)

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,48,Avondale,Chicago.
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,115,South End,Boston.
2,OZ5857,Illinois,4,3,Apartment,100.0,51,150,Avondale,Chicago.
3,HY8797,California,2,1,Apartment,75.0,4,125,SoMa,San Francisco.
4,VN7858,Massachusetts,2,1,House,88.0,23,64,West Roxbury,Boston.

### (c) 불필요한 문자 제거하기

- `replace()`: 문자열을 치환하는 함수
  - `regex`(`regular expression`): 정규 표현식
  - `regex=True`: 정규표현식 패턴 치환(기본값)
  - `regex=False`: 단순 문자 치환

In [ ]:
airbnb_df['city'].unique()

array([' Chicago.', ' Boston.', ' San Francisco.', ' Los Angeles.'],
      dtype=object)

In [ ]:
# city 앞에 있는 화이트 스페이스 제거
airbnb_df['city'] = airbnb_df['city'].str.strip()

In [ ]:
airbnb_df['city'].unique()

array(['Chicago.', 'Boston.', 'San Francisco.', 'Los Angeles.'],
      dtype=object)

In [ ]:
# city에 있는 .을 제거
airbnb_df['city'] = airbnb_df['city'].str.replace('.', '', regex=False)

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,48,Avondale,Chicago
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,115,South End,Boston
2,OZ5857,Illinois,4,3,Apartment,100.0,51,150,Avondale,Chicago
3,HY8797,California,2,1,Apartment,75.0,4,125,SoMa,San Francisco
4,VN7858,Massachusetts,2,1,House,88.0,23,64,West Roxbury,Boston

### (d) 문자열 탐색하기

- `str.startswith()` : 특정 문자열로 시작하는지 확인
- `str.endswith()` : 특정 문자열로 끝나는지 확인
- `str.contains()` : 특정 문자열이 포함되어 있는지 확인

In [ ]:
# id가 B로 시작하는 데이터 찾기
airbnb_df[airbnb_df['id'].str.startswith('B')]

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,48,Avondale,Chicago
20,BV5351,California,2,1,Apartment,98.0,16,100,Silver Lake,Los Angeles
33,BT8735,California,8,4,Apartment,92.0,75,198,The Castro,San Francisco
37,BF2157,Massachusetts,2,1,Condominium,99.0,19,108,South Boston,Boston
46,BK9521,California,1,1,Apartment,100.0,1,100,SoMa,San Francisco
63,BM7841,Illinois,2,1,Apartment,99.0,84,125,Wicker Park,Chicago
164,BT6049,Illinois,8,4,Other,96.0,45,89,Bronzeville,Chicago
166,BO4490,Illinois,2,1,House,96.0,14,109,South Shore,Chicago
176,BC7046,California,6,2,House,93.0,14,139,South LA,Los Angeles
204,BP2305,California,2,1,Apartment,100.0,1,150,Altadena,Los Angeles
285,BJ1202,Massachusetts,2,1,Apartment,95.0,34,188,Beacon Hill,Boston
318,BO4312,Illinois,6,3,House,98.0,13,115,Avondale,Chicago
362,BG5317,Massachusetts,2,1,Apartment,92.0,11,150,South End,Boston
371,BG4878,Massachusetts,2,2,Apartment,94.0,28,55,Dorchester,Boston
399,BN1735,Massachusetts,5,2,Apartment,96.0,21,129,Hyde Park,Boston
446,BT3164,Illinois,2,1,Apartment,95.0,4,119,Humboldt Park,Chicago
471,BR7193,California,2,1,Apartment,98.0,38,74,Hollywood Hills,Los Angeles
474,BV3279,California,4,2,House,96.0,39,195,Del Rey,Los Angeles
476,BY7562,Massachusetts,2,1,Apartment,100.0,6,100,Jamaica Plain,Boston
478,BG8077,Illinois,2,1,Apartment,99.0,76,48,Wrigleyville,Chicago
479,BR2480,Illinois,2,1,Apartment,95.0,24,64,West Town/Noble Square,Chicago
508,BI5135,Illinois,4,2,Condominium,95.0,37,147,Ukrainian Village,Chicago
541,BZ3596,Illinois,2,1,Apartment,91.0,28,119,Lakeview,Chicago
563,BS3036,Illinois,2,1,Condominium,100.0,16,59,Irving Park,Chicago
565,BM4661,Massachusetts,2,1,Apartment,100.0,1,139,South End,Boston
601,BZ3596,Illinois,2,1,House,89.0,30,119,Lakeview,Chicago
604,BV4439,California,2,1,Apartment,95.0,96,124,Potrero Hill,San Francisco
606,BX9112,California,4,2,Apartment,94.0,118,100,Hollywood,Los Angeles

In [ ]:
# city가 o로 끝나는 데이터 찾기
airbnb_df[airbnb_df['city'].str.endswith('o')]

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,48,Avondale,Chicago
2,OZ5857,Illinois,4,3,Apartment,100.0,51,150,Avondale,Chicago
3,HY8797,California,2,1,Apartment,75.0,4,125,SoMa,San Francisco
5,PP4626,California,2,1,Apartment,92.0,211,129,Western Addition/NOPA,San Francisco
8,GU6250,California,2,1,Apartment,100.0,1,139,Mission District,San Francisco
...,...,...,...,...,...,...,...,...,...,...
699,WE7914,California,2,1,House,100.0,19,122,Balboa Terrace,San Francisco
700,LG6908,California,2,1,Apartment,100.0,3,195,Financial District,San Francisco
703,VM9239,Illinois,4,1,Apartment,96.0,11,139,Lincoln Park,Chicago
706,RJ4302,California,4,1,Other,100.0,21,139,Noe Valley,San Francisco
711,EE8333,Illinois,2,1,House,80.0,15,115,Lakeview,Chicago

In [ ]:
# state에 Mass가 포함된 데이터 찾기
airbnb_df[airbnb_df['state'].str.contains('Mass')]

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,115,South End,Boston
4,VN7858,Massachusetts,2,1,House,88.0,23,64,West Roxbury,Boston
7,JO6059,Massachusetts,2,2,Apartment,96.0,15,158,Fenway/Kenmore,Boston
14,MY4058,Massachusetts,2,1,Apartment,100.0,4,199,South Boston,Boston
15,MP5849,Massachusetts,4,2,Dorm,91.0,15,45,Allston-Brighton,Boston
...,...,...,...,...,...,...,...,...,...,...
693,IH9457,Massachusetts,2,1,House,93.0,153,122,South Boston,Boston
696,HU4579,Massachusetts,3,1,Condominium,93.0,24,108,South Boston,Boston
702,HR9207,Massachusetts,2,1,Apartment,99.0,22,125,East Boston,Boston
707,WQ9969,Massachusetts,2,2,House,100.0,1,125,Jamaica Plain,Boston
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,115,East Boston,Boston

### (e) 문자열 포맷 맞추기

- `str.len()` : 각 문자열의 길이
- `str.pad()` : 문자열 길이를 맞추기 위해 특정 문자를 채움

In [ ]:
airbnb_df.head()

,id,state,guests,beds,property_type,rating,n_reviews,price,neighborhood,city
0,BF1406,Illinois,2,1,Apartment,96.0,55,48,Avondale,Chicago
1,DB7921,Massachusetts,4,1,Apartment,NaN,0,115,South End,Boston
2,OZ5857,Illinois,4,3,Apartment,100.0,51,150,Avondale,Chicago
3,HY8797,California,2,1,Apartment,75.0,4,125,SoMa,San Francisco
4,VN7858,Massachusetts,2,1,House,88.0,23,64,West Roxbury,Boston

In [ ]:
airbnb_df['id'].str.len()

0      6
1      6
2      6
3      6
4      6
      ..
708    6
709    6
710    6
711    6
712    6
Name: id, Length: 713, dtype: int64

In [ ]:
airbnb_df['id'].str.pad(width=8, side='right', fillchar='0')

0      BF140600
1      DB792100
2      OZ585700
3      HY879700
4      VN785800
         ...
708    XG328900
709    ZR529800
710    XZ553100
711    EE833300
712    AA602400
Name: id, Length: 713, dtype: object

### (f) 범주형 데이터 타입 다루기

In [ ]:
clothes_df = pd.DataFrame({
    'size' : ['L', 'S', 'XS', 'L', 'S', 'XL', 'L', 'S', 'M', 'XS', 'M', 'M', 'XS', 'L', 'XL', 'XS', 'M', 'S', 'L', 'XL'],
    'sales' : [130, 200, 120, 120, 140, 160, 190, 90, 110, 100, 150, 180, 100, 200, 80, 140, 150, 90, 80, 130]
})

clothes_df

   size  sales
0     L    130
1     S    200
2    XS    120
3     L    120
4     S    140
5    XL    160
6     L    190
7     S     90
8     M    110
9    XS    100
10    M    150
11    M    180
12   XS    100
13    L    200
14   XL     80
15   XS    140
16    M    150
17    S     90
18    L     80
19   XL    130

In [ ]:
clothes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    20 non-null     object
 1   sales   20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

In [ ]:
clothes_df['size'] = pd.Categorical(clothes_df['size'], ordered=True, categories=['XS', 'S', 'M', 'L', 'XL'])

In [ ]:
clothes_df.sort_values(by='size')

   size  sales
9    XS    100
2    XS    120
15   XS    140
12   XS    100
1     S    200
17    S     90
4     S    140
7     S     90
16    M    150
8     M    110
10    M    150
11    M    180
13    L    200
0     L    130
6     L    190
3     L    120
18    L     80
14   XL     80
5    XL    160
19   XL    130

## (6) 데이터 전처리 : 수치 데이터 처리

### (a) 파생 변수 생성

In [ ]:
# 데이터 불러오기
patient_df = pd.read_csv('patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [ ]:
patient_df['waist_hip_ratio'] = round(patient_df['waist'] / patient_df['hip'], 2)

In [ ]:
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,waist_hip_ratio
0,50,Male,385,140,1.75,78.0,41,37,Y,0.90
1,37,Female,67,214,1.63,65.8,42,34,N,0.81
2,43,Female,100,160,1.63,63.5,40,37,N,0.92
3,32,Female,90,176,1.60,114.3,58,45,N,0.78
4,20,Male,71,164,1.83,65.8,36,29,N,0.81

### (b) 스케일링 : 정규화, 표준화

**스케일링(Scaling)**  
   - 숫자 데이터의 **단위나 범위를 일정하게 맞추는 과정**으로 서로 다른 단위를 가진 데이터를 비교 가능하게 만든다.

(정규화)

**정규화(Normalization)**  
   - 데이터를 **0과 1 사이 값**으로 변환하는 것으로 **Min-Max Normalization**이라고도 부른다.

**정규화 계산식**
   - 데이터의 최솟값은 0, 최댓값은 1로 맞추고 나머지 값들은 그 사이 비율에 맞게 변환한다.
   - 계산식:  
   $$
   \text{정규화} = \frac{(x - \min(x))}{\max(x) - \min(x)}
   $$

In [ ]:
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,waist_hip_ratio
0,50,Male,385,140,1.75,78.0,41,37,Y,0.90
1,37,Female,67,214,1.63,65.8,42,34,N,0.81
2,43,Female,100,160,1.63,63.5,40,37,N,0.92
3,32,Female,90,176,1.60,114.3,58,45,N,0.78
4,20,Male,71,164,1.83,65.8,36,29,N,0.81

In [ ]:
# height 컬럼 정규화
patient_df['height'] = (patient_df['height'] - patient_df['height'].min()) / (patient_df['height'].max() - patient_df['height'].min())

In [ ]:
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,waist_hip_ratio
0,50,Male,385,140,0.704918,78.0,41,37,Y,0.90
1,37,Female,67,214,0.508197,65.8,42,34,N,0.81
2,43,Female,100,160,0.508197,63.5,40,37,N,0.92
3,32,Female,90,176,0.459016,114.3,58,45,N,0.78
4,20,Male,71,164,0.836066,65.8,36,29,N,0.81

In [ ]:
# 정규화 확인 : 최솟값과 최댓값이 각각 0과 1
patient_df['height'].describe()

count    348.000000
mean       0.590588
std        0.163932
min        0.000000
25%        0.459016
50%        0.590164
75%        0.704918
max        1.000000
Name: height, dtype: float64

(표준화)

**표준화(Standardization, Standard Scaling)**  
   - 각 값이 **평균에 비해 얼마나 큰지 또는 작은지**를 나타내는 것으로 데이터를 변환했을 때 평균은 0, 분산은 1이 되도록 맞춘다.

**z-score 계산식**

$$
z = \frac{(x - \mu)}{\sigma}
$$

   - 데이터가 평균에서 얼마나 떨어져 있는지(거리)를 표준편차 단위로 표현한다.

In [ ]:
# 데이터 불러오기
patient_df = pd.read_csv('patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [ ]:
# height 컬럼 표준화
patient_df['height'] = (patient_df['height'] - patient_df['height'].mean()) / (patient_df['height'].std())

In [ ]:
# 표준화 확인 : mean(평균), std(표준편차) 각각 0과 1
patient_df['height'].describe()

count    3.480000e+02
mean    -9.034918e-16
std      1.000000e+00
min     -3.602650e+00
25%     -8.026005e-01
50%     -2.586253e-03
75%      6.974262e-01
max      2.497458e+00
Name: height, dtype: float64

**데이터 스케일링 정리**

1. **정규화 (Normalization)**  
  - 모든 값을 0과 1 사이 값으로 변환하여 데이터의 최솟값은 0, 최댓값은 1이 되도록 조정  

2. **표준화 (Standardization)**  
  - 각 데이터가 평균에서 얼마나 떨어져 있는지를 비교하여 평균 = 0, 표준편차 = 1이 되도록 조정

### (c) 구간화

- 데이터 구간화(binning): `cut()` 함수를 사용하여 수치형 데이터를 바탕으로 여러 개의 구간으로 구간화

**연속형 데이터를 범주형으로 구간화하기**

- `pd.cut()` 함수는 숫자 데이터를 특정 구간(bins)으로 나누어 범주형(label) 데이터로 변환할 때 사용  
  - `bins`: 나눌 구간 경계값을 리스트 형태로 지정  
  - `labels`: 각 구간에 붙일 이름을 지정  
  - `right=False`: 구간의 오른쪽 경계를 포함하지 않도록 설정(기본값은 `True`)
  - `include_lowest=True` : 최솟값을 첫 구간에 포함시킬지 여부 설정

**코드 예시**
```python
df['새로운_컬럼'] = pd.cut(df['숫자형_컬럼'],
                          bins=[경계1, 경계2, 경계3, ...],
                          right=False,
                          labels=['라벨1', '라벨2', '라벨3', ...])

In [ ]:
# 데이터 불러오기
patient_df = pd.read_csv('patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [ ]:
patient_df['age'].describe()

count    348.000000
mean      43.505747
std       13.473101
min       20.000000
25%       33.000000
50%       42.000000
75%       55.000000
max       69.000000
Name: age, dtype: float64

In [ ]:
patient_df['age_group'] = pd.cut(patient_df['age'],
                                 bins=[20, 30, 40, 50, 60, 70],
                                 right=False,
                                 labels=['20s', '30s', '40s', '50s', '60s'])

In [ ]:
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,age_group
0,50,Male,385,140,1.75,78.0,41,37,Y,50s
1,37,Female,67,214,1.63,65.8,42,34,N,30s
2,43,Female,100,160,1.63,63.5,40,37,N,40s
3,32,Female,90,176,1.60,114.3,58,45,N,30s
4,20,Male,71,164,1.83,65.8,36,29,N,20s

### (d) apply 활용

- `apply()` : DataFrame이나 Series에 함수를 적용
- `lambda` : 이름 없는 간단한 함수를 정의할 때 사용  
- `apply(lambda ...)` : 간단한 함수를 즉석에서 만들어 각 요소나 행/열에 적용  

**사용 형태**

```python
df['새로운_컬럼'] = df['기존_컬럼'].apply(lambda x: 함수식(x))

(예시1)

In [ ]:
# 데이터 프레임 생성하기
df = pd.DataFrame([[1, 9],
                  [4, 16]]
                  , columns=['column1', 'column2'])
df

   column1  column2
0        1        9
1        4       16

In [ ]:
np.sqrt(4)

np.float64(2.0)

In [ ]:
df['column2'].apply(np.sqrt)

0    3.0
1    4.0
Name: column2, dtype: float64

(예시2)

In [ ]:
patient_df = pd.read_csv('patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [ ]:
def age_group(x):
    if 10 <= x < 20:
        return '10s'
    elif 20 <= x < 30:
        return '20s'
    elif 30 <= x < 40:
        return '30s'
    elif 40 <= x < 50:
        return '40s'
    elif 50 <= x < 60:
        return '50s'
    else:
        return '60s'

In [ ]:
patient_df['age_group'] = patient_df['age'].apply(age_group)

In [ ]:
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,age_group
0,50,Male,385,140,1.75,78.0,41,37,Y,50s
1,37,Female,67,214,1.63,65.8,42,34,N,30s
2,43,Female,100,160,1.63,63.5,40,37,N,40s
3,32,Female,90,176,1.60,114.3,58,45,N,30s
4,20,Male,71,164,1.83,65.8,36,29,N,20s

(예시3)

In [ ]:
patient_df['height'].apply(lambda x: x * 2)

0      3.50
1      3.26
2      3.26
3      3.20
4      3.66
       ...
343    3.70
344    3.46
345    3.36
346    3.46
347    3.30
Name: height, Length: 348, dtype: float64

(예시4)

In [ ]:
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,age_group
0,50,Male,385,140,1.75,78.0,41,37,Y,50s
1,37,Female,67,214,1.63,65.8,42,34,N,30s
2,43,Female,100,160,1.63,63.5,40,37,N,40s
3,32,Female,90,176,1.60,114.3,58,45,N,30s
4,20,Male,71,164,1.83,65.8,36,29,N,20s

In [ ]:
patient_df['bmi'] = round(patient_df['weight'] / patient_df['height']**2, 1)
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,age_group,bmi
0,50,Male,385,140,1.75,78.0,41,37,Y,50s,25.5
1,37,Female,67,214,1.63,65.8,42,34,N,30s,24.8
2,43,Female,100,160,1.63,63.5,40,37,N,40s,23.9
3,32,Female,90,176,1.60,114.3,58,45,N,30s,44.6
4,20,Male,71,164,1.83,65.8,36,29,N,20s,19.6

In [ ]:
patient_df['bmi'].apply(lambda x: 'Y' if x > 30 else 'N')

0      N
1      N
2      N
3      Y
4      N
      ..
343    N
344    Y
345    Y
346    N
347    N
Name: bmi, Length: 348, dtype: object

In [ ]:
def is_obese(x, n_lower, n_upper):
    if n_lower <= x <= n_upper:
        return 'Y'
    else:
        return 'N'

In [ ]:
patient_df['bmi'].apply(lambda x: is_obese(x, 25, 60))

0      Y
1      N
2      N
3      Y
4      N
      ..
343    Y
344    Y
345    Y
346    N
347    Y
Name: bmi, Length: 348, dtype: object

## (7) 날짜와 시간 데이터 다루기

(날짜 데이터 타입 설정하기)

- `pd.to_datetime()`: 문자열이나 숫자 등 다양한 형태의 데이터를 날짜·시간(`datetime`) 객체로 변환하여 변환된 데이터는 시계열 분석, 시간 연산, 날짜 인덱싱 등에 활용할 수 있다.

In [ ]:
order_df = pd.read_csv('order.csv')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaN,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00

In [ ]:
order_df.dtypes

order_time                      object
category                        object
product_name                    object
price                          float64
quantity                         int64
sales                          float64
days_for_shipping(expected)      int64
shipping_time                   object
dtype: object

In [ ]:
# 날짜 데이터 타입으로 변경
order_df['order_time'] = pd.to_datetime(order_df['order_time'])
order_df['shipping_time'] = pd.to_datetime(order_df['shipping_time'])

In [ ]:
order_df.dtypes

order_time                     datetime64[ns]
category                               object
product_name                           object
price                                 float64
quantity                                int64
sales                                 float64
days_for_shipping(expected)             int64
shipping_time                  datetime64[ns]
dtype: object

In [ ]:
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00

In [ ]:
order_df.isna().sum().sum()

np.int64(1)

In [ ]:
order_df.isna().sum()

order_time                     1
category                       0
product_name                   0
price                          0
quantity                       0
sales                          0
days_for_shipping(expected)    0
shipping_time                  0
dtype: int64

In [ ]:
order_df.shape

(18050, 8)

In [ ]:
order_df.dropna(inplace=True)

In [ ]:
order_df.shape

(18049, 8)

In [ ]:
# date
order_df['order_time'].dt.date

0        2015-01-01
2        2015-01-01
3        2015-01-01
4        2015-01-01
5        2015-01-01
            ...
18045    2018-01-31
18046    2018-01-31
18047    2018-01-31
18048    2018-01-31
18049    2018-01-31
Name: order_time, Length: 18049, dtype: object

In [ ]:
# year
order_df['order_time'].dt.year

0        2015
2        2015
3        2015
4        2015
5        2015
         ...
18045    2018
18046    2018
18047    2018
18048    2018
18049    2018
Name: order_time, Length: 18049, dtype: int32

In [ ]:
# month
order_df['order_time'].dt.month

0        1
2        1
3        1
4        1
5        1
        ..
18045    1
18046    1
18047    1
18048    1
18049    1
Name: order_time, Length: 18049, dtype: int32

In [ ]:
# day
order_df['order_time'].dt.day

0         1
2         1
3         1
4         1
5         1
         ..
18045    31
18046    31
18047    31
18048    31
18049    31
Name: order_time, Length: 18049, dtype: int32

[참고 : 요일](https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.weekday.html)

In [ ]:
# 요일 : day_of_week, weekday(0 : 월요일)
order_df['order_time'].dt.day_of_week

0        3
2        3
3        3
4        3
5        3
        ..
18045    2
18046    2
18047    2
18048    2
18049    2
Name: order_time, Length: 18049, dtype: int32

In [ ]:
# 년월
order_df['order_time'].dt.to_period('M')

0        2015-01
2        2015-01
3        2015-01
4        2015-01
5        2015-01
          ...
18045    2018-01
18046    2018-01
18047    2018-01
18048    2018-01
18049    2018-01
Name: order_time, Length: 18049, dtype: period[M]

In [ ]:
# hour
order_df['order_time'].dt.hour

0         4
2         2
3        19
4         3
5        22
         ..
18045    10
18046    21
18047    17
18048    12
18049    16
Name: order_time, Length: 18049, dtype: int32

In [ ]:
# minute
order_df['order_time'].dt.minute

0        54
2        27
3        58
4        51
5         4
         ..
18045    20
18046    53
18047    20
18048    26
18049    59
Name: order_time, Length: 18049, dtype: int32

In [ ]:
# second
order_df['order_time'].dt.second

0        0
2        0
3        0
4        0
5        0
        ..
18045    0
18046    0
18047    0
18048    0
18049    0
Name: order_time, Length: 18049, dtype: int32

(날짜 데이터 형식 지정하기)

[참고](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)

In [ ]:
# 2015-01-01 04:54:00 -> 2015년 01월 01일 04시 54분 00초
order_df['order_time'] = order_df['order_time'].dt.strftime('%Y년 %m월 %d일 %H시 %M분 %S초')
order_df['shipping_time'] = order_df['shipping_time'].dt.strftime('%Y년 %m월 %d일 %H시 %M분 %S초')

In [ ]:
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015년 01월 01일 04시 54분 00초,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015년 01월 07일 19시 07분 00초
2,2015년 01월 01일 02시 27분 00초,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015년 01월 05일 13시 15분 00초
3,2015년 01월 01일 19시 58분 00초,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015년 01월 05일 12시 08분 00초
4,2015년 01월 01일 03시 51분 00초,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015년 01월 04일 20시 06분 00초
5,2015년 01월 01일 22시 04분 00초,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,3,150.00,3,2015년 01월 03일 19시 47분 00초

(날짜와 시간을 더하고 빼기)

In [ ]:
order_df = pd.read_csv('order.csv')
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaN,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00

In [ ]:
order_df.dtypes

order_time                      object
category                        object
product_name                    object
price                          float64
quantity                         int64
sales                          float64
days_for_shipping(expected)      int64
shipping_time                   object
dtype: object

In [ ]:
# 날짜 데이터 형식으로 바꾸기
order_df['order_time'] = pd.to_datetime(order_df['order_time'])
order_df['shipping_time'] = pd.to_datetime(order_df['shipping_time'])

In [ ]:
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00

In [ ]:
order_df['days_for_shipping(actual)'] = order_df['shipping_time'] - order_df['order_time']

In [ ]:
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual)
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00,6 days 14:13:00
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00,NaT
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00,4 days 10:48:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00,3 days 16:10:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00,3 days 16:15:00

In [ ]:
order_df.dtypes

order_time                      datetime64[ns]
category                                object
product_name                            object
price                                  float64
quantity                                 int64
sales                                  float64
days_for_shipping(expected)              int64
shipping_time                   datetime64[ns]
days_for_shipping(actual)      timedelta64[ns]
dtype: object

In [ ]:
order_df['days_for_shipping(expected)'] = pd.to_timedelta(order_df['days_for_shipping(expected)'], unit='D')

In [ ]:
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual)
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6 days,2015-01-07 19:07:00,6 days 14:13:00
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6 days,2015-01-04 09:47:00,NaT
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6 days,2015-01-05 13:15:00,4 days 10:48:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6 days,2015-01-05 12:08:00,3 days 16:10:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6 days,2015-01-04 20:06:00,3 days 16:15:00

In [ ]:
order_df['late_shipping'] = order_df['days_for_shipping(expected)'] < order_df['days_for_shipping(actual)']

In [ ]:
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual),late_shipping
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6 days,2015-01-07 19:07:00,6 days 14:13:00,True
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6 days,2015-01-04 09:47:00,NaT,False
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6 days,2015-01-05 13:15:00,4 days 10:48:00,False
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6 days,2015-01-05 12:08:00,3 days 16:10:00,False
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6 days,2015-01-04 20:06:00,3 days 16:15:00,False

In [ ]:
order_df['late_shipping'].value_counts()

late_shipping
False    14846
True      3204
Name: count, dtype: int64

In [ ]:
order_df['late_shipping'].value_counts(normalize=True)

late_shipping
False    0.822493
True     0.177507
Name: proportion, dtype: float64

In [ ]:
order_df.shape

(18050, 10)

In [ ]:
# 늦게 배송된 경우
order_df[order_df['late_shipping'] == True]

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual),late_shipping
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6 days,2015-01-07 19:07:00,6 days 14:13:00,True
6,2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4 days,2015-01-05 17:05:00,4 days 09:23:00,True
10,2015-01-01 08:03:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,4 days,2015-01-06 12:32:00,5 days 04:29:00,True
15,2015-01-01 12:57:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,4 days,2015-01-05 15:14:00,4 days 02:17:00,True
22,2015-01-02 05:04:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,4 days,2015-01-07 12:48:00,5 days 07:44:00,True
...,...,...,...,...,...,...,...,...,...,...
18027,2018-01-28 11:34:00,Women's Clothing,Summer dresses,215.82,1,215.82,4 days,2018-02-02 12:51:00,5 days 01:17:00,True
18032,2018-01-29 14:11:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-04 20:04:00,6 days 05:53:00,True
18034,2018-01-29 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,4 days,2018-02-04 16:17:00,6 days 03:51:00,True
18043,2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 18:53:00,6 days 00:09:00,True
18049,2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 20:32:00,6 days 03:33:00,True

## (8) 데이터 합치기

### (a) concat(): 같은 형식의 데이터 합치기

In [ ]:
english_df1 = pd.DataFrame({
    'name' : ['A', 'B', 'C'],
    'english_score' : [50, 89, 68]
})

english_df2 = pd.DataFrame({
    'name' : ['D', 'E', 'F'],
    'english_score' : [88, 91, 72]
})

math_df = pd.DataFrame({
    'name' : ['A', 'B', 'C', 'D', 'E', 'F'],
    'math_score' : [86, 31, 91, 75, 68, 80]
})

In [ ]:
english_df1

  name  english_score
0    A             50
1    B             89
2    C             68

In [ ]:
english_df2

  name  english_score
0    D             88
1    E             91
2    F             72

In [ ]:
pd.concat([english_df1, english_df2])

  name  english_score
0    A             50
1    B             89
2    C             68
0    D             88
1    E             91
2    F             72

In [ ]:
english_df = pd.concat([english_df1, english_df2], ignore_index=True)
english_df

  name  english_score
0    A             50
1    B             89
2    C             68
3    D             88
4    E             91
5    F             72

In [ ]:
math_df

  name  math_score
0    A          86
1    B          31
2    C          91
3    D          75
4    E          68
5    F          80

In [ ]:
pd.concat([english_df, math_df], axis=1)

  name  english_score name  math_score
0    A             50    A          86
1    B             89    B          31
2    C             68    C          91
3    D             88    D          75
4    E             91    E          68
5    F             72    F          80

### (b) merge(): 컬럼 기준 데이터 합치기

**조인 연산(Join)**

- 두 데이터셋에 공통으로 존재하는 값을 기준(Key)으로 데이터를 하나로 합치는 것으로 Key(키)는 데이터 간 연결고리 역할을 하는 기준 값이다.(예: 고객 ID, 주문 번호 등)

- **조인의 종류**  
  - Inner Join(기본값) : 두 데이터 모두에 존재하는 키만 결합
  - Left Outer Join : 왼쪽 데이터는 모두 살리고, 오른쪽 데이터에서 일치하는 키만 결합  
  - Right Outer Join : 오른쪽 데이터는 모두 살리고, 왼쪽 데이터에서 일치하는 키만 결합  
  - Full Outer Join : 양쪽 데이터의 모든 키를 포함해 결합  

- **실무 활용**  
  - 주로 **Inner Join**과 **Left Outer Join**이 많이 사용된다.

In [ ]:
employee_df = pd.read_csv('employee.csv')
survey_df = pd.read_csv('survey.csv')

In [ ]:
employee_df.head()

       id department  location             role resign
0  101929         HR     China            Staff      Y
1  101625    Finance        US  Senior Director      N
2  100298         HR     China          Manager      N
3  101870    Finance  Colombia          Manager      N
4  101318         IT     Japan     Senior Staff      N

In [ ]:
survey_df.head()

       id department  career  teamwork  reward  environment
0  101355         HR       5         4       5            4
1  100077      Sales       2         2       4            3
2  101844    Finance       2         3       1            5
3  101929         HR       2         3       2            3
4  101888         HR       4         4       3            3

In [ ]:
employee_df['id'].count(), employee_df['id'].nunique()

(np.int64(100), 100)

In [ ]:
survey_df['id'].count(), survey_df['id'].nunique()

(np.int64(76), 76)

In [ ]:
pd.merge(employee_df, survey_df, on='id', how='inner')

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,HR,2,3,2,3
1,101625,Finance,US,Senior Director,N,Finance,2,2,3,1
2,101318,IT,Japan,Senior Staff,N,IT,2,3,5,5
3,100936,HR,Japan,Manager,Y,HR,3,2,2,4
4,100125,HR,Korea,Senior Staff,N,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...,...
71,102031,IT,Colombia,Senior Manager,Y,IT,1,3,3,1
72,100476,HR,Colombia,Senior Manager,Y,HR,1,2,3,5
73,100226,HR,UK,Senior Manager,N,HR,2,2,3,4
74,101331,IT,Korea,Manager,N,IT,3,5,4,4
75,100233,Sales,Japan,Staff,N,Sales,4,2,2,5

In [ ]:
pd.merge(employee_df, survey_df, on='id', how='left')

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,HR,2.0,3.0,2.0,3.0
1,101625,Finance,US,Senior Director,N,Finance,2.0,2.0,3.0,1.0
2,100298,HR,China,Manager,N,NaN,NaN,NaN,NaN,NaN
3,101870,Finance,Colombia,Manager,N,NaN,NaN,NaN,NaN,NaN
4,101318,IT,Japan,Senior Staff,N,IT,2.0,3.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...
95,100476,HR,Colombia,Senior Manager,Y,HR,1.0,2.0,3.0,5.0
96,100226,HR,UK,Senior Manager,N,HR,2.0,2.0,3.0,4.0
97,101331,IT,Korea,Manager,N,IT,3.0,5.0,4.0,4.0
98,100036,HR,UK,Manager,N,NaN,NaN,NaN,NaN,NaN
99,100233,Sales,Japan,Staff,N,Sales,4.0,2.0,2.0,5.0

In [ ]:
pd.merge(employee_df, survey_df, on='id', how='right')

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,101355,HR,US,Director,N,HR,5,4,5,4
1,100077,Sales,Australia,Staff,Y,Sales,2,2,4,3
2,101844,Finance,UK,Senior Manager,N,Finance,2,3,1,5
3,101929,HR,China,Staff,Y,HR,2,3,2,3
4,101888,HR,Australia,Senior Staff,N,HR,4,4,3,3
...,...,...,...,...,...,...,...,...,...,...
71,101449,HR,Korea,Manager,N,HR,4,3,3,5
72,101423,Finance,US,Manager,Y,Finance,1,2,1,4
73,101098,IT,France,Senior Staff,Y,IT,1,3,4,4
74,100618,IT,Turkey,Senior Staff,N,IT,5,2,1,2
75,100488,Finance,Japan,Senior Staff,Y,Finance,5,4,1,5

In [ ]:
pd.merge(employee_df, survey_df, on='id', how='outer')

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,100036,HR,UK,Manager,N,NaN,NaN,NaN,NaN,NaN
1,100077,Sales,Australia,Staff,Y,Sales,2.0,2.0,4.0,3.0
2,100083,IT,Australia,Senior Staff,N,IT,5.0,3.0,4.0,4.0
3,100106,IT,Korea,Senior Staff,N,IT,4.0,2.0,5.0,1.0
4,100118,Sales,UK,Senior Staff,Y,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
95,101927,IT,Australia,Staff,N,NaN,NaN,NaN,NaN,NaN
96,101929,HR,China,Staff,Y,HR,2.0,3.0,2.0,3.0
97,101968,IT,France,Senior Manager,N,IT,2.0,2.0,2.0,1.0
98,101975,Sales,Turkey,Staff,N,Sales,1.0,5.0,5.0,5.0
99,102031,IT,Colombia,Senior Manager,Y,IT,1.0,3.0,3.0,1.0

In [ ]:
employee_df.head()

       id department  location             role resign
0  101929         HR     China            Staff      Y
1  101625    Finance        US  Senior Director      N
2  100298         HR     China          Manager      N
3  101870    Finance  Colombia          Manager      N
4  101318         IT     Japan     Senior Staff      N

In [ ]:
survey_df.head()

       id department  career  teamwork  reward  environment
0  101355         HR       5         4       5            4
1  100077      Sales       2         2       4            3
2  101844    Finance       2         3       1            5
3  101929         HR       2         3       2            3
4  101888         HR       4         4       3            3

(survey_df의 id를 employee_id로 변경)

In [ ]:
#survey_df.columns = ['employee_id', 'department', 'career', 'teamwork', 'reward', 'environment']

Index(['id', 'department', 'career', 'teamwork', 'reward', 'environment'], dtype='object')

In [ ]:
survey_df.rename(columns={'id' : 'employee_id'}, inplace=True)

In [ ]:
survey_df.head()

   employee_id department  career  teamwork  reward  environment
0       101355         HR       5         4       5            4
1       100077      Sales       2         2       4            3
2       101844    Finance       2         3       1            5
3       101929         HR       2         3       2            3
4       101888         HR       4         4       3            3

In [ ]:
pd.merge(employee_df, survey_df, left_on='id', right_on='employee_id', how='left')

,id,department_x,location,role,resign,employee_id,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,101929.0,HR,2.0,3.0,2.0,3.0
1,101625,Finance,US,Senior Director,N,101625.0,Finance,2.0,2.0,3.0,1.0
2,100298,HR,China,Manager,N,NaN,NaN,NaN,NaN,NaN,NaN
3,101870,Finance,Colombia,Manager,N,NaN,NaN,NaN,NaN,NaN,NaN
4,101318,IT,Japan,Senior Staff,N,101318.0,IT,2.0,3.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
95,100476,HR,Colombia,Senior Manager,Y,100476.0,HR,1.0,2.0,3.0,5.0
96,100226,HR,UK,Senior Manager,N,100226.0,HR,2.0,2.0,3.0,4.0
97,101331,IT,Korea,Manager,N,101331.0,IT,3.0,5.0,4.0,4.0
98,100036,HR,UK,Manager,N,NaN,NaN,NaN,NaN,NaN,NaN
99,100233,Sales,Japan,Staff,N,100233.0,Sales,4.0,2.0,2.0,5.0

### (c) join(): 인덱스 기준 데이터 합치기

In [ ]:
employee_df = pd.read_csv('employee.csv')
employee_df.set_index('id', inplace=True)
employee_df.head()

       department  location             role resign
id
101929         HR     China            Staff      Y
101625    Finance        US  Senior Director      N
100298         HR     China          Manager      N
101870    Finance  Colombia          Manager      N
101318         IT     Japan     Senior Staff      N

In [ ]:
survey_df = pd.read_csv('survey.csv')
survey_df.set_index('id', inplace=True)
survey_df.head()

       department  career  teamwork  reward  environment
id
101355         HR       5         4       5            4
100077      Sales       2         2       4            3
101844    Finance       2         3       1            5
101929         HR       2         3       2            3
101888         HR       4         4       3            3

- join은 default(기본값)이 left

In [ ]:
employee_df.join(survey_df, lsuffix='_x', rsuffix='_y')

,department_x,location,role,resign,department_y,career,teamwork,reward,environment
id,,,,,,,,,
101929,HR,China,Staff,Y,HR,2.0,3.0,2.0,3.0
101625,Finance,US,Senior Director,N,Finance,2.0,2.0,3.0,1.0
100298,HR,China,Manager,N,NaN,NaN,NaN,NaN,NaN
101870,Finance,Colombia,Manager,N,NaN,NaN,NaN,NaN,NaN
101318,IT,Japan,Senior Staff,N,IT,2.0,3.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...
100476,HR,Colombia,Senior Manager,Y,HR,1.0,2.0,3.0,5.0
100226,HR,UK,Senior Manager,N,HR,2.0,2.0,3.0,4.0
101331,IT,Korea,Manager,N,IT,3.0,5.0,4.0,4.0
100036,HR,UK,Manager,N,NaN,NaN,NaN,NaN,NaN
100233,Sales,Japan,Staff,N,Sales,4.0,2.0,2.0,5.0

In [ ]:
employee_df.join(survey_df, lsuffix='_x', rsuffix='_y', how='inner')

,department_x,location,role,resign,department_y,career,teamwork,reward,environment
id,,,,,,,,,
101929,HR,China,Staff,Y,HR,2,3,2,3
101625,Finance,US,Senior Director,N,Finance,2,2,3,1
101318,IT,Japan,Senior Staff,N,IT,2,3,5,5
100936,HR,Japan,Manager,Y,HR,3,2,2,4
100125,HR,Korea,Senior Staff,N,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...
102031,IT,Colombia,Senior Manager,Y,IT,1,3,3,1
100476,HR,Colombia,Senior Manager,Y,HR,1,2,3,5
100226,HR,UK,Senior Manager,N,HR,2,2,3,4
101331,IT,Korea,Manager,N,IT,3,5,4,4
100233,Sales,Japan,Staff,N,Sales,4,2,2,5

(merge() vs. join())

- `merge()` : 컬럼명을 기준으로 데이터를 합치는 것
- `join()` : 인덱스를 기준으로 데이터를 합치는 것
- 그런데 그 반대의 경우도 가능은 하다.

### 조인한 데이터로 새로운 인사이트 얻기

In [ ]:
employee_df = pd.read_csv('employee.csv')
employee_df.head()

       id department  location             role resign
0  101929         HR     China            Staff      Y
1  101625    Finance        US  Senior Director      N
2  100298         HR     China          Manager      N
3  101870    Finance  Colombia          Manager      N
4  101318         IT     Japan     Senior Staff      N

In [ ]:
survey_df = pd.read_csv('survey.csv')
survey_df.head()

       id department  career  teamwork  reward  environment
0  101355         HR       5         4       5            4
1  100077      Sales       2         2       4            3
2  101844    Finance       2         3       1            5
3  101929         HR       2         3       2            3
4  101888         HR       4         4       3            3

In [ ]:
company_df = pd.merge(employee_df, survey_df, on='id', how='left')
company_df.head()

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,HR,2.0,3.0,2.0,3.0
1,101625,Finance,US,Senior Director,N,Finance,2.0,2.0,3.0,1.0
2,100298,HR,China,Manager,N,NaN,NaN,NaN,NaN,NaN
3,101870,Finance,Colombia,Manager,N,NaN,NaN,NaN,NaN,NaN
4,101318,IT,Japan,Senior Staff,N,IT,2.0,3.0,5.0,5.0

In [ ]:
company_df.shape

(100, 10)

In [ ]:
company_df['resign'].value_counts()

resign
N    74
Y    26
Name: count, dtype: int64

In [ ]:
company_df['resign'].value_counts(normalize=True)

resign
N    0.74
Y    0.26
Name: proportion, dtype: float64

- 퇴사한 직원들과 퇴사하지 않은 직원들의 정보를 비교한 결과, 커리어, 팀워크, 보상, 환경 모든 면에서 퇴자하지 않은 직원들의 평균 만족도가 퇴사한 직원들보다 전반적으로 더 높은 것을 알 수 있다.

In [ ]:
# 퇴사한 직원들
condition = (company_df['resign'] == 'Y')
company_df[condition].describe()

                  id     career   teamwork     reward  environment
count      26.000000  19.000000  19.000000  19.000000    19.000000
mean   100920.423077   2.210526   2.736842   3.052632     3.210526
std       648.867393   1.134262   1.240166   1.393385     1.512134
min    100077.000000   1.000000   1.000000   1.000000     1.000000
25%    100336.500000   1.000000   2.000000   2.000000     2.000000
50%    100766.000000   2.000000   3.000000   3.000000     3.000000
75%    101585.000000   3.000000   3.500000   4.000000     4.500000
max    102031.000000   5.000000   5.000000   5.000000     5.000000

In [ ]:
# 퇴사하지 않은 직원들
company_df[~condition].describe()

                  id     career   teamwork     reward  environment
count      74.000000  57.000000  57.000000  57.000000    57.000000
mean   101132.216216   3.228070   2.964912   3.140351     3.315789
std       595.628119   1.267978   1.335837   1.444677     1.489941
min    100036.000000   1.000000   1.000000   1.000000     1.000000
25%    100630.250000   2.000000   2.000000   2.000000     2.000000
50%    101223.500000   3.000000   3.000000   3.000000     3.000000
75%    101685.500000   4.000000   4.000000   5.000000     5.000000
max    101975.000000   5.000000   5.000000   5.000000     5.000000

## (9) 집계 및 요약 분석

### (a) 그룹화 : groupby

In [ ]:
netflix_df = pd.read_csv('netflix.csv')
netflix_df.head()

                  title        genre     release  runtime  score language
0           Dark Forces     Thriller  2020-08-21       81    2.6  Spanish
1     Leyla Everlasting       Comedy  2020-12-04      112    3.7  Turkish
2    Sardar Ka Grandson       Comedy  2021-05-18      139    4.1    Hindi
3  Searching for Sheela  Documentary  2021-04-22       58    4.1  English
4              The Call        Drama  2020-11-27      112    4.1   Korean

In [ ]:
netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     230 non-null    object
 1   genre     230 non-null    object
 2   release   230 non-null    object
 3   runtime   230 non-null    int64
 4   score     230 non-null    float64
 5   language  230 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 10.9+ KB

In [ ]:
netflix_df['genre'].nunique()

5

In [ ]:
netflix_df['genre'].unique()

array(['Thriller', 'Comedy', 'Documentary', 'Drama', 'Romantic comedy'],
      dtype=object)

In [ ]:
netflix_df.groupby(['genre']).size()

genre
Comedy             33
Documentary        80
Drama              59
Romantic comedy    27
Thriller           31
dtype: int64

- `numeric_only=True` : 수치형 데이터에 대해서

In [ ]:
netflix_df.groupby(['genre']).mean(numeric_only=True)

                    runtime     score
genre
Comedy            95.575758  5.518182
Documentary       81.262500  6.941250
Drama            106.440678  6.267797
Romantic comedy  101.555556  5.722222
Thriller         106.774194  5.687097

- 특정 컬럼에 대해서 계산

In [ ]:
netflix_df.groupby(['genre'])['score'].mean()

genre
Comedy             5.518182
Documentary        6.941250
Drama              6.267797
Romantic comedy    5.722222
Thriller           5.687097
Name: score, dtype: float64

### (b) 다양한 통계 계산

- `groupby`는 그룹별로 다양한 집계 함수(`size`, `count`, `mean`, `sum`, `max`, `min` 등)를 적용할 수 있으며, `agg()`를 사용하면 여러 통계값을 한 번에 계산할 수 있다.
  - `size` : 전체 행 개수
  - `count` : 값 개수
  - `mean`, `sum`, `max`, `min` : 대표적인 수치 집계 함수
  - `agg` : 여러 통계 지표 동시에 계산 가능

In [ ]:
netflix_df.head()

                  title        genre     release  runtime  score language
0           Dark Forces     Thriller  2020-08-21       81    2.6  Spanish
1     Leyla Everlasting       Comedy  2020-12-04      112    3.7  Turkish
2    Sardar Ka Grandson       Comedy  2021-05-18      139    4.1    Hindi
3  Searching for Sheela  Documentary  2021-04-22       58    4.1  English
4              The Call        Drama  2020-11-27      112    4.1   Korean

In [ ]:
# 장르별 평점
netflix_df.groupby(['genre'])['score'].mean()

genre
Comedy             5.518182
Documentary        6.941250
Drama              6.267797
Romantic comedy    5.722222
Thriller           5.687097
Name: score, dtype: float64

In [ ]:
# 장르별 평점(agg 사용)
netflix_df.groupby(['genre'])['score'].agg('mean')

genre
Comedy             5.518182
Documentary        6.941250
Drama              6.267797
Romantic comedy    5.722222
Thriller           5.687097
Name: score, dtype: float64

In [ ]:
# 장르별 점수의 평균, 최댓값, 최솟값(agg 사용)
netflix_df.groupby(['genre'])['score'].agg(['mean', 'max', 'min'])

                     mean  max  min
genre
Comedy           5.518182  7.2  3.7
Documentary      6.941250  9.0  4.1
Drama            6.267797  7.9  4.1
Romantic comedy  5.722222  6.8  4.1
Thriller         5.687097  7.3  2.6

In [ ]:
# 장르별 점수의 평균, 런타임의 최솟값과 최댓값
netflix_df.groupby(['genre']).agg({'score':'mean', 'runtime':['min', 'max']})

                    score runtime
                     mean     min  max
genre
Comedy           5.518182      30  139
Documentary      6.941250      16  144
Drama            6.267797      17  151
Romantic comedy  5.722222      85  131
Thriller         5.687097      81  149

### (c) 정렬

- `sort_values` : 데이터 프레임이나 시리즈를 특정 컬럼(또는 인덱스) 기준으로 정렬
  - `by`: 정렬할 컬럼 지정
  - `ascending=True`: 오름차순(기본값)
  - `ascending=False`: 내림차순

In [ ]:
# 장르별 점수의 평균, 런타임의 평균
netflix_df.groupby(['genre']).agg({'score':'mean', 'runtime':'mean'}).sort_values(by='score', ascending=False)

                    score     runtime
genre
Documentary      6.941250   81.262500
Drama            6.267797  106.440678
Romantic comedy  5.722222  101.555556
Thriller         5.687097  106.774194
Comedy           5.518182   95.575758

### (d) 문자열 집계/요약

In [ ]:
netflix_df.head()

                  title        genre     release  runtime  score language
0           Dark Forces     Thriller  2020-08-21       81    2.6  Spanish
1     Leyla Everlasting       Comedy  2020-12-04      112    3.7  Turkish
2    Sardar Ka Grandson       Comedy  2021-05-18      139    4.1    Hindi
3  Searching for Sheela  Documentary  2021-04-22       58    4.1  English
4              The Call        Drama  2020-11-27      112    4.1   Korean

In [ ]:
netflix_df.groupby(['genre'])['title'].apply(lambda x: ', '.join(x))

genre
Comedy             Leyla Everlasting, Sardar Ka Grandson, What Ha...
Documentary        Searching for Sheela, After the Raid, Hello Pr...
Drama              The Call, Finding Agnes, The Binding, The Day ...
Romantic comedy    Whipped, Just Say Yes, Squared Love, Desperado...
Thriller           Dark Forces, Secret Obsession, The Girl on the...
Name: title, dtype: object

### (e) 멀티 인덱스

In [ ]:
netflix_df.head()

                  title        genre     release  runtime  score language
0           Dark Forces     Thriller  2020-08-21       81    2.6  Spanish
1     Leyla Everlasting       Comedy  2020-12-04      112    3.7  Turkish
2    Sardar Ka Grandson       Comedy  2021-05-18      139    4.1    Hindi
3  Searching for Sheela  Documentary  2021-04-22       58    4.1  English
4              The Call        Drama  2020-11-27      112    4.1   Korean

In [ ]:
netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     230 non-null    object
 1   genre     230 non-null    object
 2   release   230 non-null    object
 3   runtime   230 non-null    int64
 4   score     230 non-null    float64
 5   language  230 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 10.9+ KB

In [ ]:
netflix_df['release'] = pd.to_datetime(netflix_df['release'])

In [ ]:
netflix_df['release'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 230 entries, 0 to 229
Series name: release
Non-Null Count  Dtype
--------------  -----
230 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.9 KB

In [ ]:
netflix_df['year'] = netflix_df['release'].dt.year

In [ ]:
netflix_df.head()

                  title        genre    release  runtime  score language  year
0           Dark Forces     Thriller 2020-08-21       81    2.6  Spanish  2020
1     Leyla Everlasting       Comedy 2020-12-04      112    3.7  Turkish  2020
2    Sardar Ka Grandson       Comedy 2021-05-18      139    4.1    Hindi  2021
3  Searching for Sheela  Documentary 2021-04-22       58    4.1  English  2021
4              The Call        Drama 2020-11-27      112    4.1   Korean  2020

In [ ]:
netflix_df.groupby(['genre', 'year'])['score'].mean()

genre            year
Comedy           2019    5.625000
                 2020    5.571429
                 2021    5.228571
Documentary      2019    6.920000
                 2020    7.177778
                 2021    6.378571
Drama            2019    6.335714
                 2020    6.055556
                 2021    6.533333
Romantic comedy  2019    5.871429
                 2020    5.687500
                 2021    5.600000
Thriller         2019    5.842857
                 2020    5.666667
                 2021    5.566667
Name: score, dtype: float64

In [ ]:
netflix_df.groupby(['genre', 'year'])[['score', 'runtime']].mean()

                         score     runtime
genre           year
Comedy          2019  5.625000   84.250000
                2020  5.571429  100.857143
                2021  5.228571  104.428571
Documentary     2019  6.920000   82.033333
                2020  7.177778   82.611111
                2021  6.378571   76.142857
Drama           2019  6.335714  107.857143
                2020  6.055556  103.000000
                2021  6.533333  110.500000
Romantic comedy 2019  5.871429   92.714286
                2020  5.687500  105.187500
                2021  5.600000  102.500000
Thriller        2019  5.842857  105.428571
                2020  5.666667  106.944444
                2021  5.566667  107.833333

### (f) 피벗 테이블

**피벗 테이블(Pivot Table)**

- 피벗 테이블은 데이터를 집계·요약하여 한눈에 보기 쉽게 만드는 표
- `pandas`의 `pivot_table()` 함수를 활용해 다양한 형태로 표 생성 가능
- 인덱스와 컬럼을 활용해 데이터 구조화

```python
pd.pivot_table(데이터프레임,
              values='계산할 컬럼',
              index='행기준',
              columns='열기준',
              aggfunc='집계방법')
```

In [ ]:
netflix_df.head()

                  title        genre    release  runtime  score language  year
0           Dark Forces     Thriller 2020-08-21       81    2.6  Spanish  2020
1     Leyla Everlasting       Comedy 2020-12-04      112    3.7  Turkish  2020
2    Sardar Ka Grandson       Comedy 2021-05-18      139    4.1    Hindi  2021
3  Searching for Sheela  Documentary 2021-04-22       58    4.1  English  2021
4              The Call        Drama 2020-11-27      112    4.1   Korean  2020

In [ ]:
# 연도별 장르별 평점(점수의 평균)
pd.pivot_table(netflix_df,
               values='score',
               index='year',
               columns='genre',
               aggfunc='mean')

genre    Comedy  Documentary     Drama  Romantic comedy  Thriller
year
2019   5.625000     6.920000  6.335714         5.871429  5.842857
2020   5.571429     7.177778  6.055556         5.687500  5.666667
2021   5.228571     6.378571  6.533333         5.600000  5.566667

### (g) 시간 단위 리샘플링

In [ ]:
order_df = pd.read_csv('order.csv', parse_dates=['order_time', 'shipping_time'])
order_df.head()

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00

In [ ]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18050 entries, 0 to 18049
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   order_time                   18049 non-null  datetime64[ns]
 1   category                     18050 non-null  object
 2   product_name                 18050 non-null  object
 3   price                        18050 non-null  float64
 4   quantity                     18050 non-null  int64
 5   sales                        18050 non-null  float64
 6   days_for_shipping(expected)  18050 non-null  int64
 7   shipping_time                18050 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(2), object(2)
memory usage: 1.1+ MB

In [ ]:
order_df.dropna(inplace=True)

In [ ]:
order_df.shape

(18049, 8)

In [ ]:
order_df.set_index('order_time', inplace=True)

In [ ]:
order_df.head()

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
2015-01-01 22:04:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,3,150.00,3,2015-01-03 19:47:00

In [ ]:
order_df.resample('YE').sum(numeric_only=True)

                price  quantity       sales  days_for_shipping(expected)
order_time
2015-12-31  823262.88     13784  1232529.88                        30802
2016-12-31  826870.17     13617  1229005.71                        30403
2017-12-31  877373.97     10469  1173778.74                        26063
2018-12-31   34428.66       217    34428.66                         1075

In [ ]:
order_df.resample('ME').sum(numeric_only=True)

                price  quantity      sales  days_for_shipping(expected)
order_time
2015-01-31   69256.79      1180  104624.20                         2615
2015-02-28   59156.44      1037   88549.87                         2276
2015-03-31   73245.51      1183  108959.04                         2611
2015-04-30   68007.98      1089   98467.21                         2551
2015-05-31   68640.97      1172  103706.92                         2646
2015-06-30   69010.02      1098  100028.38                         2536
2015-07-31   74171.81      1155  107817.04                         2608
2015-08-31   65600.13      1143   99348.51                         2578
2015-09-30   67185.93      1120  100843.76                         2561
2015-10-31   72363.38      1176  108434.62                         2624
2015-11-30   66369.08      1210  104384.77                         2545
2015-12-31   70254.84      1221  107365.56                         2651
2016-01-31   69211.77      1188  105821.32                         2581
2016-02-29   63595.03      1066   93628.94                         2428
2016-03-31   65312.12      1140   99401.65                         2543
2016-04-30   68013.96      1101  100219.52                         2495
2016-05-31   70790.81      1211  107323.47                         2540
2016-06-30   69916.97      1039   99322.65                         2484
2016-07-31   69915.98      1106  101884.51                         2579
2016-08-31   70153.77      1172  105321.57                         2640
2016-09-30   63756.07      1121   96210.90                         2449
2016-10-31   73087.48      1213  108594.66                         2591
2016-11-30   74675.57      1087  106485.72                         2558
2016-12-31   68440.64      1173  104790.80                         2515
2017-01-31   64626.83      1155   99072.56                         2574
2017-02-28   62191.10      1125   97310.67                         2420
2017-03-31   74382.67      1155  107929.79                         2620
2017-04-30   74147.66      1062  103750.15                         2594
2017-05-31   79057.56      1089  112424.71                         2587
2017-06-30   68672.43       973   96450.17                         2430
2017-07-31   73752.08      1101  108228.75                         2541
2017-08-31   76288.65      1104  112607.36                         2584
2017-09-30   86386.14      1036  117305.87                         2528
2017-10-31  105609.86       242  106439.72                         1117
2017-11-30   63161.57       210   63161.57                         1030
2017-12-31   49097.42       217   49097.42                         1038
2018-01-31   34428.66       217   34428.66                         1075

In [ ]:
order_df.resample('D').sum(numeric_only=True)

              price  quantity    sales  days_for_shipping(expected)
order_time
2015-01-01  2429.79        33  3219.62                           82
2015-01-02  1889.80        34  2829.55                           78
2015-01-03  2379.76        45  3859.43                           90
2015-01-04  1804.82        42  3129.60                           84
2015-01-05  2282.82        30  2985.72                           80
...             ...       ...      ...                          ...
2018-01-27  1510.74         7  1510.74                           38
2018-01-28  1510.74         7  1510.74                           29
2018-01-29  1510.74         7  1510.74                           40
2018-01-30  1510.74         7  1510.74                           36
2018-01-31  1510.74         7  1510.74                           35

[1127 rows x 4 columns]

# 실습

## DataFrame 살펴보기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6590)

In [ ]:
# Q1: 1번
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   loan_id               600 non-null    object
 1   married_or_not        600 non-null    object
 2   self_employed_or_not  568 non-null    object
 3   applicant_income      600 non-null    int64
 4   loan_amount           589 non-null    float64
 5   property_area         600 non-null    object
 6   loan_status           600 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 32.9+ KB

In [ ]:
# Q2: 2번
loan_df.describe()

       applicant_income  loan_amount
count        600.000000   589.000000
mean        5412.161667   146.971307
std         6160.362669    85.756442
min          150.000000     9.200000
25%         2880.500000   100.700000
50%         3806.000000   128.000000
75%         5785.000000   168.300000
max        81000.000000   700.300000

In [ ]:
# Q3: 4번
loan_df.sort_values(by='applicant_income', ascending=False)

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
399,LP2317,Y,N,81000,360.3,Rural,N
323,LP2101,Y,NaN,63337,490.6,City,Y
163,LP1585,Y,N,51763,700.3,City,Y
147,LP1536,Y,N,39999,600.0,Suburb,Y
177,LP1640,Y,Y,39147,120.8,Suburb,Y
...,...,...,...,...,...,...,...
180,LP1644,Y,Y,674,168.3,Rural,Y
488,LP2603,N,N,645,113.6,Rural,Y
587,LP2949,N,NaN,416,350.6,City,N
456,LP2502,Y,NaN,210,98.2,Suburb,Y
208,LP1722,Y,N,150,135.8,Rural,N

In [ ]:
# Q4: 3번
loan_df.shape

(600, 7)

## Series 살펴보기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6605)

In [ ]:
# 데이터 불러오기
loan_df = pd.read_csv('loan.csv')
loan_df = loan_df.set_index('loan_id')
new_columns = {'married_or_not': 'married',
               'self_employed_or_not': 'self_employed',
               'applicant_income': 'income',
               'loan_amount': 'amount'}
loan_df = loan_df.rename(columns=new_columns)

In [ ]:
loan_df.head()

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y

In [ ]:
loan_df['property_area'].value_counts(normalize=True)

property_area
Suburb    0.380000
City      0.328333
Rural     0.291667
Name: proportion, dtype: float64

## 프리미어 리그 데이터 탐색하기

[링크](https://www.codeit.kr/topics/data-science-toolkit/lessons/8324?mediumTypedId=U2tpbGxQYXRoOjYyYjJjMjAyNzAwOWM1N2E1MjQwMThmYQ%3D%3D)

In [ ]:
# Q1: 3번
# Q2: 23
# Q3: 1

In [ ]:
# 라이브러리 불러오기
import pandas as pd

In [ ]:
data = pd.read_csv("tottenham_2021.csv", index_col="name")
data.head()

                 matches  minutes  goals  assists
name
Pierre Højbjerg       38     3420      2        4
Hugo Lloris           38     3420      0        0
Son Heung-Min         37     3114     17       10
Harry Kane            35     3082     23       14
Eric Dier             28     2520      0        0

(Q1)

In [ ]:
# Q1: 1. 데이터의 로우 개수는 24개, 컬럼 개수는 4개이다.
data.shape

(24, 4)

In [ ]:
# Q1: 2. matches, minutes, goals, assists 컬럼의 자료형은 모두 숫자 형태의 값으로 구성되어 있다.
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24 entries, Pierre Højbjerg to Dane Scarlett
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   matches  24 non-null     int64
 1   minutes  24 non-null     int64
 2   goals    24 non-null     int64
 3   assists  24 non-null     int64
dtypes: int64(4)
memory usage: 960.0+ bytes

In [ ]:
# Q1: 3. 경기에 가장 많이 출전한 선수는 Pierre Højbjerg와 Harry Kane이다. -> Harry Kane이 아니라 Hugo Lloris
data.sort_values(by='matches', ascending=False).head()

                 matches  minutes  goals  assists
name
Pierre Højbjerg       38     3420      2        4
Hugo Lloris           38     3420      0        0
Son Heung-Min         37     3114     17       10
Harry Kane            35     3082     23       14
Tanguy Ndombele       33     2091      3        2

In [ ]:
# Q1: 4. 참여한 경기 시간이 가장 긴 선수는 Pierre Højbjerg와 Hugo Lloris이다.
data.sort_values(by='minutes', ascending=False).head()

                 matches  minutes  goals  assists
name
Pierre Højbjerg       38     3420      2        4
Hugo Lloris           38     3420      0        0
Son Heung-Min         37     3114     17       10
Harry Kane            35     3082     23       14
Eric Dier             28     2520      0        0

(Q2)

In [ ]:
# 2020년~2021년 리그에서 가장 많은 골을 넣은 선수는 총 몇 골을 넣었나요? (숫자 값만 입력해 주세요!) : 23

In [ ]:
data.sort_values(by='goals', ascending=False).head(1)['goals']

name
Harry Kane    23
Name: goals, dtype: int64

(Q3)

In [ ]:
# 2020년~2021년 리그에서 가장 적은 시간 경기에 참여한 선수는 총 몇 분 경기를 뛰었나요? (숫자 값만 입력해 주세요!) : 1
data.sort_values(by='matches', ascending=True).head(1)['minutes']

name
Dane Scarlett    1
Name: minutes, dtype: int64

## 골을 넣은 선수는 누구?

[링크](https://www.codeit.kr/topics/data-science-toolkit/lessons/8322?mediumTypedId=U2tpbGxQYXRoOjYyYjJjMjAyNzAwOWM1N2E1MjQwMThmYQ%3D%3D)

In [ ]:
players_df = pd.read_csv("tottenham_2021.csv", index_col="name")
players_df.head()

                 matches  minutes  goals  assists
name
Pierre Højbjerg       38     3420      2        4
Hugo Lloris           38     3420      0        0
Son Heung-Min         37     3114     17       10
Harry Kane            35     3082     23       14
Eric Dier             28     2520      0        0

In [ ]:
players_df['goals'] >= 1

name
Pierre Højbjerg       True
Hugo Lloris          False
Son Heung-Min         True
Harry Kane            True
Eric Dier            False
Tanguy Ndombele       True
Sergio Reguilón      False
Toby Alderweireld     True
Serge Aurier          True
Davinson Sánchez     False
Moussa Sissoko       False
Lucas Moura           True
Ben Davies           False
Matt Doherty         False
Steven Bergwijn       True
Giovani Lo Celso      True
Gareth Bale           True
Harry Winks          False
Joe Rodon            False
Dele Alli            False
Japhet Tanganga      False
Érik Lamela           True
Carlos Vinícius       True
Dane Scarlett        False
Name: goals, dtype: bool

In [ ]:
players_df[players_df['goals'] >= 1]

                   matches  minutes  goals  assists
name
Pierre Højbjerg         38     3420      2        4
Son Heung-Min           37     3114     17       10
Harry Kane              35     3082     23       14
Tanguy Ndombele         33     2091      3        2
Toby Alderweireld       25     2240      1        0
Serge Aurier            19     1605      2        3
Lucas Moura             30     1411      3        4
Steven Bergwijn         21     1208      1        3
Giovani Lo Celso        18      945      1        1
Gareth Bale             20      920     11        2
Érik Lamela             23      717      1        0
Carlos Vinícius          9      308      1        0

In [ ]:
players_df.loc[players_df['goals'] >= 1]

                   matches  minutes  goals  assists
name
Pierre Højbjerg         38     3420      2        4
Son Heung-Min           37     3114     17       10
Harry Kane              35     3082     23       14
Tanguy Ndombele         33     2091      3        2
Toby Alderweireld       25     2240      1        0
Serge Aurier            19     1605      2        3
Lucas Moura             30     1411      3        4
Steven Bergwijn         21     1208      1        3
Giovani Lo Celso        18      945      1        1
Gareth Bale             20      920     11        2
Érik Lamela             23      717      1        0
Carlos Vinícius          9      308      1        0

## 여러 개의 조건으로 불린 인덱싱하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6607)

In [ ]:
# 데이터 불러오기
loan_df = pd.read_csv('loan.csv')
loan_df = loan_df.set_index('loan_id')
new_columns = {'married_or_not': 'married',
               'self_employed_or_not': 'self_employed',
               'applicant_income': 'income',
               'loan_amount': 'amount'}
loan_df = loan_df.rename(columns=new_columns)
loan_df.head()

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y

In [ ]:
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 600 entries, LP1003 to LP2990
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   married        600 non-null    object
 1   self_employed  568 non-null    object
 2   income         600 non-null    int64
 3   amount         589 non-null    float64
 4   property_area  600 non-null    object
 5   loan_status    600 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 32.8+ KB

In [ ]:
# 대출에 대한 조건
condition1 = loan_df['loan_status'] == 'Y'

In [ ]:
# 자영업자에 대한 조건
condition2 = loan_df['self_employed'] == 'N'

In [ ]:
# 수입에 대한 조건
condition3 = loan_df['income'] >= loan_df['income'].median()

In [ ]:
loan_df['income'].median()

3806.0

In [ ]:
loan_df[condition1 & (condition2 & condition3)]

        married self_employed  income  amount property_area loan_status
loan_id
LP1008        N             N    6000   141.4          City           Y
LP1018        Y             N    4006   168.6          City           Y
LP1032        N             N    4950   125.2          City           Y
LP1046        Y             N    5955   315.5          City           Y
LP1073        Y             N    4226   110.2          City           Y
...         ...           ...     ...     ...           ...         ...
LP2959        Y             N   12000   497.0        Suburb           Y
LP2964        Y             N    3987   157.3         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[159 rows x 6 columns]

In [ ]:
df[df['self_employed'] == 'N'].shape

(488, 6)

In [ ]:
df[df['self_employed'] != 'Y'].shape

(520, 6)

In [ ]:
df['self_employed'].value_counts(dropna=False)

self_employed
N      488
Y       80
NaN     32
Name: count, dtype: int64

## 선수 데이터 수정 및 추가하기

[링크](https://www.codeit.kr/topics/data-science-toolkit/lessons/8323?mediumTypedId=U2tpbGxQYXRoOjYyYjJjMjAyNzAwOWM1N2E1MjQwMThmYQ%3D%3D)

In [ ]:
players_df = pd.read_csv("tottenham_2122.csv", index_col="name")
players_df

                        matches  minutes  goals  assists
name
Harry Kane                 37.0     3229     17        9
Dejan Kulusevski           18.0     1276      5        8
Steven Bergwijn            25.0      518      3        1
Pierre-Emile Højbjerg      36.0     3202      2        2
Lucas Moura                34.0     1770      2        6
Davinson Sánchez           23.0     1618      2        0
Matt Doherty               15.0      864      2        4
Sergio Reguilón            25.0     1929      2        3
Ben Davies                  NaN     2542      1        1
Tanguy NDombele Alvaro      9.0      490      1        1
Cristian Romero            22.0     1850      1        0
Emerson                    31.0     2296      1        1
Hugo Lloris                38.0     3420      0        0
Eric Dier                  35.0     3071      0        0
Harry Winks                19.0      896      0        1
Giovani Lo Celso            9.0      223      0        0
Rodrigo Bentancur          17.0     1376      0        4
Joe Rodon                   3.0       86      0        0
Ryan Sessegnon             15.0     1065      0        2
Oliver Skipp               18.0     1340      0        0
Bryan Gil Salvatierra       9.0       76      0        0
Japhet Tanganga            11.0      751      0        0
Dane Scarlett               1.0        2      0        0

(특정 행에 값 추가하기)

In [ ]:
players_df.loc['Son Heung-Min'] = [35, 3051, 23, 7]

In [ ]:
players_df

                        matches  minutes  goals  assists
name
Harry Kane                 37.0     3229     17        9
Dejan Kulusevski           18.0     1276      5        8
Steven Bergwijn            25.0      518      3        1
Pierre-Emile Højbjerg      36.0     3202      2        2
Lucas Moura                34.0     1770      2        6
Davinson Sánchez           23.0     1618      2        0
Matt Doherty               15.0      864      2        4
Sergio Reguilón            25.0     1929      2        3
Ben Davies                  NaN     2542      1        1
Tanguy NDombele Alvaro      9.0      490      1        1
Cristian Romero            22.0     1850      1        0
Emerson                    31.0     2296      1        1
Hugo Lloris                38.0     3420      0        0
Eric Dier                  35.0     3071      0        0
Harry Winks                19.0      896      0        1
Giovani Lo Celso            9.0      223      0        0
Rodrigo Bentancur          17.0     1376      0        4
Joe Rodon                   3.0       86      0        0
Ryan Sessegnon             15.0     1065      0        2
Oliver Skipp               18.0     1340      0        0
Bryan Gil Salvatierra       9.0       76      0        0
Japhet Tanganga            11.0      751      0        0
Dane Scarlett               1.0        2      0        0
Son Heung-Min              35.0     3051     23        7

(특정 행·열에 있는 값 대체하기)

In [ ]:
players_df.loc['Ben Davies', 'matches'] = 29

In [ ]:
players_df

                        matches  minutes  goals  assists
name
Harry Kane                 37.0     3229     17        9
Dejan Kulusevski           18.0     1276      5        8
Steven Bergwijn            25.0      518      3        1
Pierre-Emile Højbjerg      36.0     3202      2        2
Lucas Moura                34.0     1770      2        6
Davinson Sánchez           23.0     1618      2        0
Matt Doherty               15.0      864      2        4
Sergio Reguilón            25.0     1929      2        3
Ben Davies                 29.0     2542      1        1
Tanguy NDombele Alvaro      9.0      490      1        1
Cristian Romero            22.0     1850      1        0
Emerson                    31.0     2296      1        1
Hugo Lloris                38.0     3420      0        0
Eric Dier                  35.0     3071      0        0
Harry Winks                19.0      896      0        1
Giovani Lo Celso            9.0      223      0        0
Rodrigo Bentancur          17.0     1376      0        4
Joe Rodon                   3.0       86      0        0
Ryan Sessegnon             15.0     1065      0        2
Oliver Skipp               18.0     1340      0        0
Bryan Gil Salvatierra       9.0       76      0        0
Japhet Tanganga            11.0      751      0        0
Dane Scarlett               1.0        2      0        0
Son Heung-Min              35.0     3051     23        7

(특정 열에 값 일괄 추가하기)

In [ ]:
players_df['team'] = 'Tottenham'

In [ ]:
players_df

                        matches  minutes  goals  assists       team
name
Harry Kane                 37.0     3229     17        9  Tottenham
Dejan Kulusevski           18.0     1276      5        8  Tottenham
Steven Bergwijn            25.0      518      3        1  Tottenham
Pierre-Emile Højbjerg      36.0     3202      2        2  Tottenham
Lucas Moura                34.0     1770      2        6  Tottenham
Davinson Sánchez           23.0     1618      2        0  Tottenham
Matt Doherty               15.0      864      2        4  Tottenham
Sergio Reguilón            25.0     1929      2        3  Tottenham
Ben Davies                 29.0     2542      1        1  Tottenham
Tanguy NDombele Alvaro      9.0      490      1        1  Tottenham
Cristian Romero            22.0     1850      1        0  Tottenham
Emerson                    31.0     2296      1        1  Tottenham
Hugo Lloris                38.0     3420      0        0  Tottenham
Eric Dier                  35.0     3071      0        0  Tottenham
Harry Winks                19.0      896      0        1  Tottenham
Giovani Lo Celso            9.0      223      0        0  Tottenham
Rodrigo Bentancur          17.0     1376      0        4  Tottenham
Joe Rodon                   3.0       86      0        0  Tottenham
Ryan Sessegnon             15.0     1065      0        2  Tottenham
Oliver Skipp               18.0     1340      0        0  Tottenham
Bryan Gil Salvatierra       9.0       76      0        0  Tottenham
Japhet Tanganga            11.0      751      0        0  Tottenham
Dane Scarlett               1.0        2      0        0  Tottenham
Son Heung-Min              35.0     3051     23        7  Tottenham

## 데이터 삭제하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6610)

In [ ]:
# 데이터 불러오기
loan_df = pd.read_csv('loan.csv')
loan_df = loan_df.set_index('loan_id')
new_columns = {'married_or_not': 'married',
               'self_employed_or_not': 'self_employed',
               'applicant_income': 'income',
               'loan_amount': 'amount'}
loan_df = loan_df.rename(columns=new_columns)
loan_df.head()

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y

In [ ]:
loan_df.drop('loan_status', axis=1)

        married self_employed  income  amount property_area
loan_id
LP1003        Y             N    4583   128.4         Rural
LP1005        Y             Y    3000    66.0          City
LP1006        Y             N    2583   120.5          City
LP1008        N             N    6000   141.4          City
LP1011        Y             Y    5417   267.4          City
...         ...           ...     ...     ...           ...
LP2974        Y             N    3232   108.6         Rural
LP2979        Y             N    4106    40.7         Rural
LP2983        Y             N    8072   253.4          City
LP2984        Y             N    7583   187.6          City
LP2990        N             Y    4583   133.2        Suburb

[600 rows x 5 columns]

## 결측값 처리하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6614)

In [ ]:
cellphone_df = pd.read_csv('cellphone.csv')
cellphone_df.head()

   brand                    name  size   price  battery  weight  year
0  apple       iPhone 14 (128GB)  6.1"  1250.0     3729   172.0  2022
1  apple       iPhone 14 (256GB)  6.1"  1400.0     3729   172.0  2022
2  Apple       iPhone 14 (512GB)  6.1"  1700.0     3729   172.0  2022
3  apple  iPhone 14 Plus (128GB)  6.7"  1350.0     4325   203.0  2022
4  APPLE  iPhone 14 Plus (256GB)  6.7"  1500.0     4325   203.0  2022

In [ ]:
# 결측치 확인하기
cellphone_df.isna().sum()

brand      0
name       0
size       0
price      0
battery    0
weight     3
year       0
dtype: int64

- iPhone 13 mini가 누락되어 있는데, 아이폰 13 미니의 무게는 140g이므로 140으로 결측값을 채울 수 있다.

In [ ]:
cellphone_df['weight'] = cellphone_df['weight'].fillna(140)

In [ ]:
cellphone_df[cellphone_df['year'] == 2021]

,brand,name,size,price,battery,weight,year
26,apple,iPhone 13 (128GB),"6.1""",1090.0,3227,173.0,2021
27,Apple,iPhone 13 (256GB),"6.1""",1230.0,3227,173.0,2021
28,apple,iPhone 13 (512GB),"6.1""",1500.0,3227,173.0,2021
29,APPLE,iPhone 13 Pro (128GB),"6.1""",1350.0,3095,203.0,2021
30,Apple,iPhone 13 Pro (256GB),"6.1""",1490.0,3095,203.0,2021
31,Apple,iPhone 13 Pro (512GB),"6.1""",1760.0,3095,203.0,2021
32,Apple,iPhone 13 Pro (1TB),"6.1""",2030.0,3095,203.0,2021
33,apple,iPhone 13 Pro Max (128GB),"6.7""",1490.0,4352,238.0,2021
34,Apple,iPhone 13 Pro Max (256GB),"6.7""",1630.0,4352,238.0,2021
35,Apple,iPhone 13 Pro Max (512GB),"6.7""",1900.0,4352,238.0,2021
36,Apple,iPhone 13 Pro Max (1TB),"6.7""",2170.0,4352,238.0,2021
37,Apple,iPhone 13 mini (128GB),"5.4""",950.0,2406,140.0,2021
38,Apple,iPhone 13 mini (256GB),"5.4""",1090.0,2406,140.0,2021
39,APPLE,iPhone 13 mini (512GB),"5.4""",1360.0,2406,140.0,2021
40,SAMSUNG,Galaxy A12 (32GB),"6.5""",275.0,5000,205.0,2021
41,samsung,Galaxy S21 (256GB),"6.2""",999.9,4000,169.0,2021
42,SAMSUNG,Galaxy S21 Ultra (256GB),"6.8""",1452.0,5000,227.0,2021
43,samsung,Galaxy S21 Ultra (512GB),"6.8""",1599.4,5000,227.0,2021
44,SAMSUNG,Galaxy S21+ (256GB),"6.7""",1199.0,4800,200.0,2021
45,SAMSUNG,Galaxy Z Flip3 (256GB),"6.7""",1254.0,3300,183.0,2021
46,Samsung,Galaxy Z Fold3 (256GB),"7.6""",1998.7,4400,271.0,2021
47,samsung,Galaxy Z Fold3 (512GB),"7.6""",2097.7,4400,271.0,2021
48,samsung,Galaxy Z Fold3 Thom Browne Edition (512GB),"7.6""",3960.0,4400,271.0,2021

## 중복값 처리하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6617)

In [ ]:
# 데이터 불러오기
cellphone_df = pd.read_csv('cellphone.csv')
cellphone_df.head()

   brand                    name  size   price  battery  weight  year
0  apple       iPhone 14 (128GB)  6.1"  1250.0     3729   172.0  2022
1  apple       iPhone 14 (256GB)  6.1"  1400.0     3729   172.0  2022
2  Apple       iPhone 14 (512GB)  6.1"  1700.0     3729   172.0  2022
3  apple  iPhone 14 Plus (128GB)  6.7"  1350.0     4325   203.0  2022
4  APPLE  iPhone 14 Plus (256GB)  6.7"  1500.0     4325   203.0  2022

In [ ]:
cellphone_df.shape

(70, 7)

In [ ]:
cellphone_df.duplicated().sum()

np.int64(4)

In [ ]:
cellphone_df[cellphone_df.duplicated(keep=False)]

      brand                       name  size   price  battery  weight  year
18  samsung        Galaxy S22+ (256GB)  6.6"  1199.0     4500   195.0  2022
19  samsung        Galaxy S22+ (256GB)  6.6"  1199.0     4500   195.0  2022
22  samsung     Galaxy Z Fold4 (256GB)  7.6"  1998.7     4400   263.0  2022
23  samsung     Galaxy Z Fold4 (256GB)  7.6"  1998.7     4400   263.0  2022
55    apple  iPhone 12 Pro Max (128GB)  6.7"  1490.0     3687   228.0  2020
56    apple  iPhone 12 Pro Max (128GB)  6.7"  1490.0     3687   228.0  2020
57    apple  iPhone 12 Pro Max (128GB)  6.7"  1490.0     3687   228.0  2020

In [ ]:
cellphone_df = cellphone_df.drop_duplicates()
cellphone_df

,brand,name,size,price,battery,weight,year
0,apple,iPhone 14 (128GB),"6.1""",1250.0,3729,172.0,2022
1,apple,iPhone 14 (256GB),"6.1""",1400.0,3729,172.0,2022
2,Apple,iPhone 14 (512GB),"6.1""",1700.0,3729,172.0,2022
3,apple,iPhone 14 Plus (128GB),"6.7""",1350.0,4325,203.0,2022
4,APPLE,iPhone 14 Plus (256GB),"6.7""",1500.0,4325,203.0,2022
...,...,...,...,...,...,...,...
65,SAMSUNG,Galaxy S20 Ultra (512GB),"6.9""",1793.0,5000,220.0,2020
66,samsung,Galaxy S20+ (256GB),"6.7""",1353.0,4500,186.0,2020
67,SAMSUNG,Galaxy Z Flip2 (256GB),"6.7""",1650.0,3300,183.0,2020
68,Samsung,Galaxy Z Fold2 (256GB),"7.6""",1892.0,4500,282.0,2020
69,samsung,Galaxy Z Fold2 Thom Browne Edition (256GB),"7.6""",3960.0,4500,282.0,2020

In [ ]:
cellphone_df.shape

(66, 7)

## 이상점 처리하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6620)

In [ ]:
# 데이터 불러오기
cellphone_df = pd.read_csv('cellphone.csv')
cellphone_df.head()

   brand                    name  size   price  battery  weight  year
0  apple       iPhone 14 (128GB)  6.1"  1250.0     3729   172.0  2022
1  apple       iPhone 14 (256GB)  6.1"  1400.0     3729   172.0  2022
2  Apple       iPhone 14 (512GB)  6.1"  1700.0     3729   172.0  2022
3  apple  iPhone 14 Plus (128GB)  6.7"  1350.0     4325   203.0  2022
4  APPLE  iPhone 14 Plus (256GB)  6.7"  1500.0     4325   203.0  2022

In [ ]:
cellphone_df.shape

(70, 7)

In [ ]:
# IQR 기반 이상점 처리하기
q3 = cellphone_df['price'].quantile(0.75)
q1 = cellphone_df['price'].quantile(0.25)

iqr = q3 - q1

lower_limit = q1 - 1.5*iqr
upper_limit = q3 + 1.5*iqr

# 정상 범위
condition1 = cellphone_df['price'] >= lower_limit
condition2 = cellphone_df['price'] <= upper_limit
cellphone_df = cellphone_df[condition1 & condition2]
cellphone_df

      brand                      name  size   price  battery  weight  year
0     apple         iPhone 14 (128GB)  6.1"  1250.0     3729   172.0  2022
1     apple         iPhone 14 (256GB)  6.1"  1400.0     3729   172.0  2022
2     Apple         iPhone 14 (512GB)  6.1"  1700.0     3729   172.0  2022
3     apple    iPhone 14 Plus (128GB)  6.7"  1350.0     4325   203.0  2022
4     APPLE    iPhone 14 Plus (256GB)  6.7"  1500.0     4325   203.0  2022
..      ...                       ...   ...     ...      ...     ...   ...
64  samsung  Galaxy S20 Ultra (256GB)  6.9"  1595.0     5000   220.0  2020
65  SAMSUNG  Galaxy S20 Ultra (512GB)  6.9"  1793.0     5000   220.0  2020
66  samsung       Galaxy S20+ (256GB)  6.7"  1353.0     4500   186.0  2020
67  SAMSUNG    Galaxy Z Flip2 (256GB)  6.7"  1650.0     3300   183.0  2020
68  Samsung    Galaxy Z Fold2 (256GB)  7.6"  1892.0     4500   282.0  2020

[67 rows x 7 columns]

In [ ]:
cellphone_df.shape

(67, 7)

## 문자 데이터 처리하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6624)

In [ ]:
cellphone_df = pd.read_csv('cellphone.csv')
cellphone_df.head()

   brand                    name  size   price  battery  weight  year
0  apple       iPhone 14 (128GB)  6.1"  1250.0     3729   172.0  2022
1  apple       iPhone 14 (256GB)  6.1"  1400.0     3729   172.0  2022
2  Apple       iPhone 14 (512GB)  6.1"  1700.0     3729   172.0  2022
3  apple  iPhone 14 Plus (128GB)  6.7"  1350.0     4325   203.0  2022
4  APPLE  iPhone 14 Plus (256GB)  6.7"  1500.0     4325   203.0  2022

In [ ]:
# 대소문자 표기 통일하기
cellphone_df['brand'] = cellphone_df['brand'].str.capitalize()

In [ ]:
# model 컬럼 생성하기
cellphone_df['model'] = cellphone_df['name'].str.split('(').str[0].str.strip()

In [ ]:
# capacity 컬럼 생성하기
cellphone_df['capacity'] = cellphone_df['name'].str.split('(').str[1].str.replace(')','')

In [ ]:
# name 컬럼 삭제하기
cellphone_df.drop(columns='name', inplace=True)

In [ ]:

# size 컬럼 숫자형으로 바꾸기
cellphone_df['size'] = cellphone_df['size'].str.replace('"', '').astype(float)

In [ ]:
cellphone_df.head()

   brand  size   price  battery  weight  year           model capacity
0  Apple   6.1  1250.0     3729   172.0  2022       iPhone 14    128GB
1  Apple   6.1  1400.0     3729   172.0  2022       iPhone 14    256GB
2  Apple   6.1  1700.0     3729   172.0  2022       iPhone 14    512GB
3  Apple   6.7  1350.0     4325   203.0  2022  iPhone 14 Plus    128GB
4  Apple   6.7  1500.0     4325   203.0  2022  iPhone 14 Plus    256GB

## 정규화

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6628)

In [ ]:
patient_df = pd.read_csv('patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [ ]:
# patient_df에서 weight 컬럼 정규화하기
patient_df['weight'] = (patient_df['weight'] - patient_df['weight'].min()) / (patient_df['weight'].max() - patient_df['weight'].min())
patient_df.head()

   age     sex  glucose  cholesterol  height    weight  hip  waist diabetes
0   50    Male      385          140    1.75  0.322927   41     37        Y
1   37  Female       67          214    1.63  0.203902   42     34        N
2   43  Female      100          160    1.63  0.181463   40     37        N
3   32  Female       90          176    1.60  0.677073   58     45        N
4   20    Male       71          164    1.83  0.203902   36     29        N

In [ ]:
# 정규화 확인: 최솟값과 최댓값이 각각 0과 1로 정규화
patient_df['weight'].describe()

count    348.000000
mean       0.352952
std        0.181349
min        0.000000
25%        0.230244
50%        0.331707
75%        0.446829
max        1.000000
Name: weight, dtype: float64

## 표준화

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6630)

In [ ]:
patient_df = pd.read_csv('patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [ ]:
patient_df['weight'] = (patient_df['weight'] - patient_df['weight'].mean()) / patient_df['weight'].std()
patient_df.head()

   age     sex  glucose  cholesterol  height    weight  hip  waist diabetes
0   50    Male      385          140    1.75 -0.165566   41     37        Y
1   37  Female       67          214    1.63 -0.821892   42     34        N
2   43  Female      100          160    1.63 -0.945626   40     37        N
3   32  Female       90          176    1.60  1.787274   58     45        N
4   20    Male       71          164    1.83 -0.821892   36     29        N

In [ ]:
# 표준화 확인: 평균이 0, 표준편차가 1로 표준화
patient_df['weight'].describe()

count    3.480000e+02
mean    -1.888655e-16
std      1.000000e+00
min     -1.946254e+00
25%     -6.766394e-01
50%     -1.171481e-01
75%      5.176593e-01
max      3.567962e+00
Name: weight, dtype: float64

## 데이터 구간화

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6632)

In [ ]:
patient_df = pd.read_csv('patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [ ]:
patient_df['bmi'] = round(patient_df['weight'] / patient_df['height']**2, 1)
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,bmi
0,50,Male,385,140,1.75,78.0,41,37,Y,25.5
1,37,Female,67,214,1.63,65.8,42,34,N,24.8
2,43,Female,100,160,1.63,63.5,40,37,N,23.9
3,32,Female,90,176,1.60,114.3,58,45,N,44.6
4,20,Male,71,164,1.83,65.8,36,29,N,19.6

In [ ]:
patient_df['bmi'].describe()

count    348.000000
mean      28.839368
std        6.710281
min       15.200000
25%       24.175000
50%       27.800000
75%       32.725000
max       55.500000
Name: bmi, dtype: float64

In [ ]:
patient_df['obesity'] = pd.cut(patient_df['bmi'],
                              bins=[15, 18.5, 25, 30, 60],
                              right=False,
                              labels=['under', 'healthy', 'over', 'obese'])

In [ ]:
patient_df.head()

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,bmi,obesity
0,50,Male,385,140,1.75,78.0,41,37,Y,25.5,over
1,37,Female,67,214,1.63,65.8,42,34,N,24.8,healthy
2,43,Female,100,160,1.63,63.5,40,37,N,23.9,healthy
3,32,Female,90,176,1.60,114.3,58,45,N,44.6,obese
4,20,Male,71,164,1.83,65.8,36,29,N,19.6,healthy

## 날짜와 시간 데이터 인덱싱하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/8315)

In [ ]:
delivery_df = pd.read_csv('delivery.csv')
delivery_df.head()

            order_time  distance  time_taken  num_of_deliveries  charge
0  2022-10-17 18:34:00       3.9          21                  1    4.68
1  2022-10-17 18:35:00       5.2          24                  1    7.02
2  2022-10-17 18:36:00       8.4          36                  2    9.53
3  2022-10-17 18:37:00       3.6          17                  1    6.21
4  2022-10-17 18:41:00       2.6          15                  1    2.44

In [ ]:
delivery_df.dtypes

order_time            object
distance             float64
time_taken             int64
num_of_deliveries      int64
charge               float64
dtype: object

In [ ]:
delivery_df['order_time'] = pd.to_datetime(delivery_df['order_time'])

In [ ]:
delivery_df.dtypes

order_time           datetime64[ns]
distance                    float64
time_taken                    int64
num_of_deliveries             int64
charge                      float64
dtype: object

In [ ]:
delivery_df[(delivery_df['order_time'].dt.year == 2022)
            & (delivery_df['order_time'].dt.month == 10)
            & (delivery_df['order_time'].dt.day == 17)]

            order_time  distance  time_taken  num_of_deliveries  charge
0  2022-10-17 18:34:00       3.9          21                  1    4.68
1  2022-10-17 18:35:00       5.2          24                  1    7.02
2  2022-10-17 18:36:00       8.4          36                  2    9.53
3  2022-10-17 18:37:00       3.6          17                  1    6.21
4  2022-10-17 18:41:00       2.6          15                  1    2.44
5  2022-10-17 18:54:00      15.2          34                  1   13.72
6  2022-10-17 18:54:00       2.4          14                  1    2.00
7  2022-10-17 18:54:00      13.7          50                  2    8.74
8  2022-10-17 18:55:00       7.6          28                  1    5.52
9  2022-10-17 18:55:00       3.3          16                  1    6.95
10 2022-10-17 19:16:00       4.7          19                  1    3.54
11 2022-10-17 19:17:00      12.5          43                  2   14.34
12 2022-10-17 19:17:00       3.0          16                  1    3.42
13 2022-10-17 19:19:00       8.5          30                  1   10.30
14 2022-10-17 19:20:00       5.2          22                  1    3.09
15 2022-10-17 19:21:00       2.1          14                  1    3.00
16 2022-10-17 19:21:00      16.5          52                  2   13.78
17 2022-10-17 19:22:00       8.3          30                  2   13.86

## 날짜와 시간을 더하고 빼기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/8317)

In [ ]:
delivery_df = pd.read_csv('delivery.csv')
delivery_df.head()

            order_time  distance  time_taken  num_of_deliveries  charge
0  2022-10-17 18:34:00       3.9          21                  1    4.68
1  2022-10-17 18:35:00       5.2          24                  1    7.02
2  2022-10-17 18:36:00       8.4          36                  2    9.53
3  2022-10-17 18:37:00       3.6          17                  1    6.21
4  2022-10-17 18:41:00       2.6          15                  1    2.44

In [ ]:
delivery_df.dtypes

order_time            object
distance             float64
time_taken             int64
num_of_deliveries      int64
charge               float64
dtype: object

In [ ]:
delivery_df['order_time'] = pd.to_datetime(delivery_df['order_time'])
delivery_df['time_taken'] = pd.to_timedelta(delivery_df['time_taken'], unit='m')

In [ ]:
delivery_df.dtypes

order_time            datetime64[ns]
distance                     float64
time_taken           timedelta64[ns]
num_of_deliveries              int64
charge                       float64
dtype: object

In [ ]:
delivery_df['delivery_time'] = delivery_df['order_time'] + delivery_df['time_taken']
delivery_df.head()

,order_time,distance,time_taken,num_of_deliveries,charge,delivery_time
0,2022-10-17 18:34:00,3.9,0 days 00:21:00,1,4.68,2022-10-17 18:55:00
1,2022-10-17 18:35:00,5.2,0 days 00:24:00,1,7.02,2022-10-17 18:59:00
2,2022-10-17 18:36:00,8.4,0 days 00:36:00,2,9.53,2022-10-17 19:12:00
3,2022-10-17 18:37:00,3.6,0 days 00:17:00,1,6.21,2022-10-17 18:54:00
4,2022-10-17 18:41:00,2.6,0 days 00:15:00,1,2.44,2022-10-17 18:56:00

## concat()

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6604)

In [ ]:
sales_2020_df = pd.read_csv('sales_2020.csv')
sales_2021_df = pd.read_csv('sales_2021.csv')
sales_2022_df = pd.read_csv('sales_2022.csv')

In [ ]:
sales_2020_df.head()

   year     month  total_orders  gross_sales  discounts  returns  total_sales
0  2020   January            73       8861.5    -129.40  -448.45      8283.65
1  2020  February            56       6908.5    -104.70  -416.20      6387.60
2  2020     March            60       5778.5    -172.20 -1017.20      4589.10
3  2020     April            70       8814.0    -281.40     0.00      8532.60
4  2020       May            54       6677.0    -185.75  -253.80      6237.45

In [ ]:
sales_2021_df.head()

   year     month  total_orders  gross_sales  discounts  returns  total_sales
0  2021   January            83      8923.00    -217.10   -26.25      8679.65
1  2021  February            69      6529.20    -161.35  -118.15      6249.70
2  2021     March            64      7442.70    -226.82    -8.80      7207.08
3  2021     April            81      9406.35    -232.28   -40.00      9134.07
4  2021       May            82      7493.90    -221.25 -1448.02      5824.63

In [ ]:
sales_2022_df.head()

   year     month  total_orders  gross_sales  discounts  returns  total_sales
0  2022   January            87      7811.75    -261.97 -1250.35      6299.43
1  2022  February            63      6523.70    -288.70   -38.70      6196.30
2  2022     March            99     13075.50    -439.85  -981.00     11654.65
3  2022     April            92      6977.00    -285.40   -10.00      6681.60
4  2022       May            96     10082.25    -460.90  -173.35      9448.00

In [ ]:
sales_df = pd.concat([sales_2020_df, sales_2021_df, sales_2022_df])
sales_df

,year,month,total_orders,gross_sales,discounts,returns,total_sales
0,2020,January,73,8861.50,-129.40,-448.45,8283.65
1,2020,February,56,6908.50,-104.70,-416.20,6387.60
2,2020,March,60,5778.50,-172.20,-1017.20,4589.10
3,2020,April,70,8814.00,-281.40,0.00,8532.60
4,2020,May,54,6677.00,-185.75,-253.80,6237.45
5,2020,June,68,9621.50,-234.45,-17.50,9369.55
6,2020,July,66,6480.00,-51.50,-469.20,5959.30
7,2020,August,55,8025.00,-258.90,-26.00,7740.10
8,2020,September,68,7075.00,-61.70,-281.00,6732.30
9,2020,October,59,5720.00,-88.00,-305.00,5327.00
10,2020,November,91,13025.00,-131.30,-323.85,12569.85
11,2020,December,116,10356.05,-149.85,-414.20,9792.00
0,2021,January,83,8923.00,-217.10,-26.25,8679.65
1,2021,February,69,6529.20,-161.35,-118.15,6249.70
2,2021,March,64,7442.70,-226.82,-8.80,7207.08
3,2021,April,81,9406.35,-232.28,-40.00,9134.07
4,2021,May,82,7493.90,-221.25,-1448.02,5824.63
5,2021,June,124,13260.80,-335.40,-1506.53,11418.87
6,2021,July,102,9274.95,-237.87,-689.98,8347.10
7,2021,August,82,7698.70,-140.57,-197.35,7360.78
8,2021,September,79,10582.85,-276.15,0.00,10306.70
9,2021,October,71,7014.50,-277.95,-294.75,6441.80
10,2021,November,140,12002.70,-414.45,-154.40,11433.85
11,2021,December,164,13683.50,-371.20,-928.35,12383.95
0,2022,January,87,7811.75,-261.97,-1250.35,6299.43
1,2022,February,63,6523.70,-288.70,-38.70,6196.30
2,2022,March,99,13075.50,-439.85,-981.00,11654.65
3,2022,April,92,6977.00,-285.40,-10.00,6681.60
4,2022,May,96,10082.25,-460.90,-173.35,9448.00
5,2022,June,85,7321.75,-186.02,-165.40,6970.33
6,2022,July,94,9739.20,-447.07,-908.75,8383.38
7,2022,August,105,8839.50,-201.67,-84.37,8553.46
8,2022,September,88,9077.45,-354.89,-853.35,7869.21
9,2022,October,97,9132.25,-279.42,-1572.55,7280.28
10,2022,November,272,23997.90,-776.84,-364.51,22856.55
11,2022,December,342,31183.90,-2269.51,-1311.18,27603.21

## merge()

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6636)

In [ ]:
asteroid_df = pd.read_csv('asteroid.csv')
asteroid_df.head()

,id,abs_magnitude,min_est_diameter,max_est_diameter,relative_velocity
0,3753583,24.922,0.027552,0.061608,78734.416695
1,3736681,21.200,0.152952,0.342011,78315.420560
2,2226514,20.100,0.253837,0.567597,103175.288522
3,3674619,21.300,0.146068,0.326618,70196.294986
4,3608670,25.100,0.025384,0.056760,26652.631636

In [ ]:
asteroid_df['id'].count(), asteroid_df['id'].nunique(), asteroid_df['id'].isna().sum()

(np.int64(342), 332, np.int64(0))

In [ ]:
asteroid_df[asteroid_df.duplicated(subset='id', keep=False)].sort_values(by='id')

,id,abs_magnitude,min_est_diameter,max_est_diameter,relative_velocity
318,2068347,19.9,0.278327,0.622358,33754.563071
272,2068347,19.9,0.278327,0.622358,46639.933456
23,2299582,18.0,0.667659,1.492932,50930.110499
53,2299582,18.0,0.667659,1.492932,72035.228706
19,2420286,18.8,0.461907,1.032856,75772.477438
244,2420286,18.8,0.461907,1.032856,67068.819561
201,2434326,18.4,0.555335,1.241767,51067.914336
47,2434326,18.4,0.555335,1.241767,72315.437481
197,2443103,18.0,0.667659,1.492932,41491.618479
221,2443103,18.0,0.667659,1.492932,59168.845131
220,2482796,19.5,0.334622,0.748238,39259.523869
148,2482796,19.5,0.334622,0.748238,54337.570517
131,3151655,22.4,0.088015,0.196807,51914.473369
262,3151655,22.4,0.088015,0.196807,64542.763989
76,3522123,20.8,0.183889,0.411188,40225.448865
93,3522123,20.8,0.183889,0.411188,46704.138440
44,3549618,21.0,0.167708,0.375008,47673.449068
125,3549618,21.0,0.167708,0.375008,95436.213643
238,3579078,19.6,0.319562,0.714562,73652.831939
284,3579078,19.6,0.319562,0.714562,80508.034282

In [ ]:
orbit_df = pd.read_csv('orbit.csv')
orbit_df.head()

   asteroid_id  orbit_id  min_orbit_inter  perihelion_dist  inclination
0      2489486        45         0.020437         0.924281    15.090005
1      2196068        38         0.026944         0.710371    59.379202
2      2177049        79         0.000143         0.546414     0.650215
3      2465617        22         0.032103         0.956639     9.111115
4      3758926         9         0.035563         0.853339    30.576089

In [ ]:
orbit_df['asteroid_id'].count(), orbit_df['asteroid_id'].nunique(), orbit_df['asteroid_id'].isna().sum()

(np.int64(150), 150, np.int64(0))

In [ ]:
nasa_df = pd.merge(asteroid_df, orbit_df, left_on='id', right_on='asteroid_id', how='inner')
nasa_df

,id,abs_magnitude,min_est_diameter,max_est_diameter,relative_velocity,asteroid_id,orbit_id,min_orbit_inter,perihelion_dist,inclination
0,2226514,20.1,0.253837,0.567597,103175.288522,2226514,54,0.015130,0.420701,2.564450
1,3674619,21.3,0.146068,0.326618,70196.294986,3674619,8,0.018203,0.355309,2.544707
2,3644702,20.2,0.242412,0.542051,111504.879722,3644702,43,0.039390,0.468663,29.290232
3,3019647,20.6,0.201630,0.450858,86093.161070,3019647,16,0.024227,0.318180,19.803694
4,2208115,20.7,0.192555,0.430566,45195.716041,2208115,29,0.013353,0.838391,23.293402
...,...,...,...,...,...,...,...,...,...,...
152,2085938,18.6,0.506471,1.132505,48435.858841,2085938,112,0.022124,0.956925,9.145916
153,3745504,21.7,0.121494,0.271669,113607.187316,3745504,23,0.023437,0.639498,5.151032
154,2468727,20.8,0.183889,0.411188,40225.448389,2468727,29,0.034385,0.509222,16.920882
155,3736502,21.4,0.139494,0.311918,60813.804409,3736502,17,0.021474,0.948154,8.061251
156,2041429,20.6,0.201630,0.450858,51264.256945,2041429,68,0.010898,0.708209,2.173195

## join()

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6638)

In [ ]:
asteroid_df = pd.read_csv('asteroid.csv', index_col='id')
orbit_df = pd.read_csv('orbit.csv', index_col='asteroid_id')

In [ ]:
asteroid_df.head()

         abs_magnitude  min_est_diameter  max_est_diameter  relative_velocity
id
3753583         24.922          0.027552          0.061608       78734.416695
3736681         21.200          0.152952          0.342011       78315.420560
2226514         20.100          0.253837          0.567597      103175.288522
3674619         21.300          0.146068          0.326618       70196.294986
3608670         25.100          0.025384          0.056760       26652.631636

In [ ]:
orbit_df.head()

             orbit_id  min_orbit_inter  perihelion_dist  inclination
asteroid_id
2489486            45         0.020437         0.924281    15.090005
2196068            38         0.026944         0.710371    59.379202
2177049            79         0.000143         0.546414     0.650215
2465617            22         0.032103         0.956639     9.111115
3758926             9         0.035563         0.853339    30.576089

In [ ]:
asteroid_df.shape, orbit_df.shape

((342, 4), (150, 4))

In [ ]:
nasa_df = asteroid_df.join(orbit_df, how='inner')
nasa_df.head()

,abs_magnitude,min_est_diameter,max_est_diameter,relative_velocity,orbit_id,min_orbit_inter,perihelion_dist,inclination
id,,,,,,,,
2226514,20.1,0.253837,0.567597,103175.288522,54,0.015130,0.420701,2.564450
3674619,21.3,0.146068,0.326618,70196.294986,8,0.018203,0.355309,2.544707
3644702,20.2,0.242412,0.542051,111504.879722,43,0.039390,0.468663,29.290232
3019647,20.6,0.201630,0.450858,86093.161070,16,0.024227,0.318180,19.803694
2208115,20.7,0.192555,0.430566,45195.716041,29,0.013353,0.838391,23.293402

In [ ]:
nasa_df.shape

(157, 8)

## 다양한 통계값 계산하기

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6600)

In [ ]:
olympic_df = pd.read_csv('olympic.csv')
olympic_df.head()

,name,sex,age,height,weight,team,noc,sport,event,medal
0,"Voldimars ""Valdemar"" Bandolowski",M,30,184.0,82.0,Denmark,DEN,Sailing,Sailing Mixed Three Person Keelboat,1st
1,Verner Blaudzun,M,30,173.0,68.0,Denmark,DEN,Cycling,Cycling Men's 100 kilometres Team Time Trial,3rd
2,Niels Christian Fredborg,M,29,176.0,75.0,Denmark,DEN,Cycling,"Cycling Men's 1,000 metres Time Trial",3rd
3,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 100 metres Freestyle,3rd
4,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 200 metres Freestyle,3rd

In [ ]:
olympic_df.groupby('sport').agg({'age' : ['min', 'max']})

                  age
                  min max
sport
Archery            19  33
Athletics          17  37
Basketball         19  27
Boxing             17  28
Canoeing           19  30
Cycling            18  33
Diving             16  29
Equestrianism      21  46
Fencing            19  35
Football           26  31
Gymnastics         14  29
Handball           20  28
Hockey             21  28
Judo               20  32
Modern Pentathlon  21  34
Rowing             17  30
Sailing            19  39
Shooting           21  39
Swimming           14  25
Volleyball         20  27
Water Polo         23  29
Weightlifting      20  35
Wrestling          19  33

## groupby

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6595)

In [ ]:
olympic_df = pd.read_csv('olympic.csv')
olympic_df.head()

,name,sex,age,height,weight,team,noc,sport,event,medal
0,"Voldimars ""Valdemar"" Bandolowski",M,30,184.0,82.0,Denmark,DEN,Sailing,Sailing Mixed Three Person Keelboat,1st
1,Verner Blaudzun,M,30,173.0,68.0,Denmark,DEN,Cycling,Cycling Men's 100 kilometres Team Time Trial,3rd
2,Niels Christian Fredborg,M,29,176.0,75.0,Denmark,DEN,Cycling,"Cycling Men's 1,000 metres Time Trial",3rd
3,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 100 metres Freestyle,3rd
4,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 200 metres Freestyle,3rd

In [ ]:
olympic_df.groupby('sport')[['height', 'weight']].mean()

                       height     weight
sport
Archery            170.000000  64.333333
Athletics          179.540541  74.373874
Basketball         186.000000  78.000000
Boxing             174.767442  64.837209
Canoeing           181.393939  80.090909
Cycling            178.888889  76.000000
Diving             169.500000  62.750000
Equestrianism      177.777778  70.444444
Fencing            177.125000  71.500000
Football           180.000000  76.000000
Gymnastics         162.727273  55.204545
Handball           182.500000  78.833333
Hockey             175.000000  69.000000
Judo               177.375000  86.916667
Modern Pentathlon  183.166667  75.833333
Rowing             183.071429  80.761905
Sailing            182.944444  78.555556
Shooting           177.476190  76.952381
Swimming           177.736111  69.388889
Volleyball         181.000000  77.833333
Water Polo         195.333333  92.000000
Weightlifting      167.074074  82.129630
Wrestling          171.783333  75.716667

## groupby와 멀티 인덱스

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6598)

In [ ]:
olympic_df = pd.read_csv('olympic.csv')
olympic_df.head()

,name,sex,age,height,weight,team,noc,sport,event,medal
0,"Voldimars ""Valdemar"" Bandolowski",M,30,184.0,82.0,Denmark,DEN,Sailing,Sailing Mixed Three Person Keelboat,1st
1,Verner Blaudzun,M,30,173.0,68.0,Denmark,DEN,Cycling,Cycling Men's 100 kilometres Team Time Trial,3rd
2,Niels Christian Fredborg,M,29,176.0,75.0,Denmark,DEN,Cycling,"Cycling Men's 1,000 metres Time Trial",3rd
3,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 100 metres Freestyle,3rd
4,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 200 metres Freestyle,3rd

In [ ]:
olympic_df.groupby(['sport', 'sex'])[['height', 'weight']].mean()

                           height     weight
sport             sex
Archery           F    166.333333  61.333333
                  M    173.666667  67.333333
Athletics         F    171.976190  65.071429
                  M    184.144928  80.036232
Basketball        F    175.666667  70.000000
                  M    196.333333  86.000000
Boxing            M    174.767442  64.837209
Canoeing          F    171.000000  68.333333
                  M    183.703704  82.703704
Cycling           M    178.888889  76.000000
Diving            F    165.166667  56.833333
                  M    173.833333  68.666667
Equestrianism     F    165.000000  55.500000
                  M    179.375000  72.312500
Fencing           F    168.000000  61.166667
                  M    180.166667  74.944444
Football          M    180.000000  76.000000
Gymnastics        F    156.222222  45.333333
                  M    167.230769  62.038462
Handball          F    170.000000  66.333333
                  M    195.000000  91.333333
Hockey            M    175.000000  69.000000
Judo              M    177.375000  86.916667
Modern Pentathlon M    183.166667  75.833333
Rowing            F    173.555556  70.166667
                  M    190.208333  88.708333
Sailing           M    182.944444  78.555556
Shooting          F    163.000000  73.000000
                  M    178.200000  77.150000
Swimming          F    170.948718  61.435897
                  M    185.757576  78.787879
Volleyball        F    172.333333  66.000000
                  M    189.666667  89.666667
Water Polo        M    195.333333  92.000000
Weightlifting     M    167.074074  82.129630
Wrestling         M    171.783333  75.716667

## 피벗 테이블

[링크](https://www.codeit.kr/topics/mastering-dataframe/lessons/6602)

In [ ]:
olympic_df = pd.read_csv('olympic.csv')
olympic_df.head()

,name,sex,age,height,weight,team,noc,sport,event,medal
0,"Voldimars ""Valdemar"" Bandolowski",M,30,184.0,82.0,Denmark,DEN,Sailing,Sailing Mixed Three Person Keelboat,1st
1,Verner Blaudzun,M,30,173.0,68.0,Denmark,DEN,Cycling,Cycling Men's 100 kilometres Team Time Trial,3rd
2,Niels Christian Fredborg,M,29,176.0,75.0,Denmark,DEN,Cycling,"Cycling Men's 1,000 metres Time Trial",3rd
3,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 100 metres Freestyle,3rd
4,Enith Sijtje Maria Brigitha (-Salle),F,21,174.0,67.0,Netherlands,NED,Swimming,Swimming Women's 200 metres Freestyle,3rd

In [ ]:
pd.pivot_table(
    olympic_df,
    index='team',
    columns='medal',
    aggfunc='size'
).fillna(0).sort_values(
    by=['1st', '2nd', '3rd', 'team'],
    ascending=False)

medal                 1st   2nd   3rd
team
Soviet Union         49.0  41.0  35.0
East Germany         40.0  25.0  25.0
United States        34.0  35.0  25.0
West Germany         10.0  12.0  17.0
Japan                 9.0   6.0  10.0
Poland                7.0   6.0  13.0
Bulgaria              6.0   9.0   7.0
Cuba                  6.0   4.0   3.0
Romania               4.0   9.0  14.0
Hungary               4.0   5.0  13.0
Finland               4.0   2.0   0.0
Sweden                4.0   1.0   0.0
Great Britain         3.0   5.0   5.0
Italy                 2.0   7.0   4.0
France                2.0   3.0   4.0
Yugoslavia            2.0   3.0   3.0
Czechoslovakia        2.0   2.0   4.0
New Zealand           2.0   1.0   1.0
South Korea           1.0   1.0   4.0
Switzerland           1.0   1.0   2.0
Norway                1.0   1.0   0.0
North Korea           1.0   1.0   0.0
Jamaica               1.0   1.0   0.0
Denmark               1.0   0.0   2.0
Mexico                1.0   0.0   1.0
Trinidad and Tobago   1.0   0.0   0.0
Canada                0.0   5.0   6.0
Belgium               0.0   3.0   3.0
Netherlands           0.0   2.0   3.0
Spain                 0.0   2.0   0.0
Portugal              0.0   2.0   0.0
Australia             0.0   1.0   4.0
Iran                  0.0   1.0   1.0
Venezuela             0.0   1.0   0.0
Mongolia              0.0   1.0   0.0
Brazil                0.0   0.0   2.0
Thailand              0.0   0.0   1.0
Puerto Rico           0.0   0.0   1.0
Pakistan              0.0   0.0   1.0
Bermuda               0.0   0.0   1.0
Austria               0.0   0.0   1.0